### ISSUE TITLE
windows state should be reopened in the last saved state

### ISSUE THREAD

**Issue by trebmuh** [Houston4444/RaySession#100]
I've got a session with "jack connections + jalv.gtk (and the GX blueAmp LV2 plugin) + XTuner.
I've got all the windows opened.
If I'm closing the session, and then, I'm opening it back, the XTuner window isn't reopened automatically and I've got to click on the "GUI" button to get it.

As a user, I expect the session to be reopened in the same state than when I closed it, hence the XTuner window should be re-opened automatically if it was opened when the session was saved last.

**Comment by Houston4444** [comment]
That is true, I am working on this feature.
However, it will only shows GUIs saved as shown, and not hide GUIs saved as hidden. Because almost programs now start hidden, and this easier and cleaner.

**Comment by Houston4444** [comment]
Implemented !
