### ISSUE TITLE
Release title with version number?

### ISSUE THREAD

**Issue by mxmilkiib** [Houston4444/RaySession#104]
Hiya, I have RaySession added to https://libreav.org/updates but I'm wondering if I could request that the release titles start with a vX.XX, like v0.10.0 - Autumn 2020 Release, so that the version number can be parsed from the title in the releases.atom feed?

**Comment by Houston4444** [comment]
I suggest to not care with the release title it self, it is not important to me.
If possible, just take the tag name (v0.10.0). Is it ?

**Comment by Houston4444** [comment]
I suggest to not care with the release title it self, it is not important to me.
If possible, just take the tag name (v0.10.0). Is it ?

**Comment by mxmilkiib** [comment]
The tag name doesn't come through in releases.atom. Entering a manual release tag title overwrites the default just-a-version-number.

https://github.com/Houston4444/RaySession/releases.atom

![image](https://user-images.githubusercontent.com/108225/105045523-e973b780-5a5f-11eb-9910-7cdb6f66297d.png)

**Comment by trebmuh** [comment]
If that can help, there is this line in the atom feed:`<id>tag:github.com,2008:Repository/112246960/v0.10.0</id>` (opened with a text editor)

**Comment by mxmilkiib** [comment]
Unfortunately it's not possible to have conditional/alternative field mappings with the Drupal Feeds aggregation module being used.

**Comment by Houston4444** [comment]
I just precede all release from 0.8.0 to the last with the version number. Is it ok this way ?

**Comment by mxmilkiib** [comment]
Awesome, thanks very much!
