### ISSUE TITLE
Template request : jack_mixer

### ISSUE THREAD

**Issue by moonshaadow** [Houston4444/RaySession#110]
Hi there.
`jack_mixer` seems to support NSM now. 
You could change the ray-hack template to a nsm one.

**Comment by Houston4444** [comment]
Hi !
I know that, unfortunately, RaySession can't know which version of jack mixer is installed, or if it has nsm support.
If jack mixer is too old, it will be launch without any session support, with no save of jack mixer at session save.
There is the possibility for packager to add the NSM jack mixer template installing a simple file  /etc/xdg/raysession/client_templates/

It has been done for librazik, example file is here (in french) http://librazik.tuxfamily.org/flyspray/index.php?do=details&task_id=1140&string=jack+mixer&search_name=&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=

**Comment by moonshaadow** [comment]
OK, that makes sense.
So is there something easily doable at jack_mixer side? And if so, do they need to be aware of that ?

**Comment by Houston4444** [comment]
I just asked Jack Mixer to add the file directly at Jack Mixer installation.
https://github.com/jack-mixer/jack_mixer/issues/129

**Comment by Houston4444** [comment]
This has been implemented at JACK mixer side. Thanks to @dsheeler .
