### ISSUE TITLE
Windows 10 support ? 

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#111]
Hello,

I weekly use Raysession and it saves me a lot of time on Linux especially for my music jams over internet.

Is there a plan to port Raysession to windows ? Or do you an alternative on windows 10 ?

BR,
Laurent

**Comment by Houston4444** [comment]
Hi.
Not at all, and I am pretty sure it is not doable to follow the NSM protocol on Windows, because of the different file path behavior.

**Comment by grammoboy2** [comment]
> Hi. Not at all, and I am pretty sure it is not doable to follow the NSM protocol on Windows, because of the different file path behavior.

Are you sure about this? Windows also has a PATH variable:
https://www.maketecheasier.com/what-is-the-windows-path/
