### ISSUE TITLE
Testers welcome for patchbay

### ISSUE THREAD

**Issue by Houston4444** [Houston4444/RaySession#112]
Hi !
the branch 'patchbay' is near ready to be merged to master. It offers one simple but consequent new feature : integrated JACK patchbay in RaySession's GUI.

User won't see this patchbay until the option "show JACK patchbay" is checked (this is the choice for the moment, maybe in future JACK patchbay could be displayed by default).

Patchbay has been copied from Carla code (from @falkTX ) with some improves, thanks to him for this great piece of software !

![patchbay_raysession](https://user-images.githubusercontent.com/3808689/115147706-990af680-a05c-11eb-94cd-dbbfb5f06a7d.png)

For the moment, there are only 3 advantages to have the patchbay directly in RaySession's GUI
* Boxes positions are memorized and replaced per session
* Boxes have icons of the corresponding NSM client
* of course: only one window for two things you generally need in a session

Some features have been added to the original Carla's patchbay:
* Most important probably: portgroups and stereo detection. Ports are automatically grouped into a portgroup if they seems to form a stereo pair. This allows faster connections, and also a more readable canvas, with less and less useless text. This improve will be proposed for PR to Carla very soon.
* wrap/unwrap boxes: you can hide all ports of a box, very useful for big groups as Ardour or Hydrogen boxes. Hide what you don't need let's you see better what you need !
* hardware boxes have specific decorations
* Boxes have their application icon if possible. Box header is a little higher, but it allows box to be consequently shorter in width in case group name is long.
* connect menu by right click: by right click on a port, you can directly connect the port to any connectable port of the canvas. Connect a port doesn't close the context menu, so you can connect to many ports quickly. It also works for portgroups.
* Clipboard: cut/copy connections of a port to another port, in port context menu. Also works for portgroups.
* filter ports: by right click in the background, you can display only Audio ports, or only MIDI ports, or all ports of course.
* when you click and drag to connect 2 ports, you also can connect with right click (while keeping left mouse button down), this way you can connect quickly one port to many others.
* with click and drag on a port, you can also move to a port with same mode (input/output), it will cut and copy connections from the first port to the second one. To prevent wrong movements, it works only if the second port has no connections
* Beziers connections lines have been reviewed to be more visible when the ports are close in abscissa and distant in ordinate
* canvas option window is a tool dialog where options take effect on place
* graceful names (default option): port names are shortened with custom rules, it doesn't uses JACK aliases. Allow boxes to be less large.
* elastic canvas (default option): the scene is automatically resized to the contents, so the view is directly optimized when group is added or moved
* option to group or not hardware A2J ports
* Box moves are animated when they are moved to their session position, when the port type filter change, or when they are joined/splitted
* Double-click anywhere in patchbay to toggle fullscreen patchbay

Regressions:
* No option to use straight lines instead of bezier lines, I find it very ugly and unusable
* No option to animate box apparition
* No theme support, only color scheme, TBH, except the "Modern Dark" default one, I find them all ugly. Adding features supporting this is quite a PITA.

The RaySession session frame is now "responsive design" to be reduced in width and allow more space to the patchbay

**Comment by Houston4444** [comment]
I'd like to
* have your impressions
* know if something make it crash
* care if port graceful names don't hide important informations
* if stereo detection doesn't works correctly for some ports (stereo detection works only looking the port names)
* anything else

Thanks a lot !

**Comment by trebmuh** [comment]
That's the third best thing in the world!

_(after sex and camembert)_

**Comment by dromer** [comment]
Few relatively minor things with the canvas:
* border around hardware devices is quite thick, feels "clunky"
* curve of patch-cables is sometimes very big, taking up a lot of space
  * curve of patch-cables doesn't always fit inside the allowed scroll window

**Comment by Houston4444** [comment]
> (after sex and camembert)

I prefer St Nectaire. But probably sex is easier with camembert.

> border around hardware devices is quite thick, feels "clunky"

I just reduced the border size from 9 to 7

> * curve of patch-cables is sometimes very big, taking up a lot of space

longer to fix, but I can try to do something.

> * curve of patch-cables doesn't always fit inside the allowed scroll window

I didn't think to that, but fix the previous point will certainly fix this bug.

**Comment by dromer** [comment]
> I just reduced the border size from 9 to 7
I think I'd go more for ~5 or so. Just enough to see a border and distinguish hw-V-sw ports, without being too massive.

> I didn't think to that, but fix the previous point will certainly fix this bug.
Yeah these two are somewhat related. Overall the curves work fine, it's that in some relative object locations they get way too big than what is suitable I think.

**Comment by Houston4444** [comment]
> I think I'd go more for ~5 or so
6 is my last price ! ;) goal was to simulate a hard case, but this is not strong.

I just made a limit to the curves lines deport in width, and also I expanded the scene margins (in width), so the problem should not happens anymore.

@trebmuh , I added the shortcut Ctrl+J to show/hide the patchbay.

**Comment by trebmuh** [comment]
> @trebmuh , I added the shortcut Ctrl+J to show/hide the patchbay.

Nice. Merci.

**Comment by dromer** [comment]
> 6 is my last price ! ;) goal was to simulate a hard case, but this is not strong.

Compromise accepted!

> I just made a limit to the curves lines deport in width, and also I expanded the scene margins (in width), so the problem should not happens anymore.

Looking good!

Only general remark for me would be to make the styling of the rest of the program match the new patchbay with a more unified and consistent look ;)

**Comment by Houston4444** [comment]
> Only general remark for me would be to make the styling of the rest of the program match the new patchbay with a more unified and consistent look ;)

Humm, that's not a little thing to do, and this relate to very subjective choices. The GUI globally follows the system style (borders, colors scheme, etc...), except almost icons are fixed to internal ones (mostly taken from KDE breeze (and breeze-dark) theme).
That won't be a priority, but for curiosity, could you be more precise about what you'd like to see differently ?

**Comment by Houston4444** [comment]
There are new features, but first be aware:[ pyjacklib](https://github.com/jackaudio/pyjacklib) is a new execution dependency !!!
This lib allows to work with JACK metadatas.

Some changes:
* prevent accidental CV Out -> Audio In  connection (dangerous for monitors). It is still possible to connect a CV Out to Audio In via port context menu -> DANGEROUS -> group_name -> port_name.  As you can see, it is near impossible to do that by error.
* Box haves 3 lines / 2 lines title depending of the smallest area (only for Carla or Non Mixer groups)
* follow the port order given by JACK metadata (tested with patroneo)
* more Metadatas will affect canvas soon

**Comment by Houston4444** [comment]
finally pyjacklib is embedded for easier packaging and easier installation from sources. So don't worry about that, thanks to @SpotlightKid and @falkTX for this lib.

**Comment by newlaurent62** [comment]
Hello,

I downloaded Raysession-patchbay.zip and install dependencies. But make fails:

`make: ***  Aucune règle pour fabriquer la cible « src/gui/ui/client_slot_2.py », nécessaire pour « raysession ». Arrêt.`

Kind Regards,
Laurent

**Comment by Houston4444** [comment]
Oups.
Fixed !

**Comment by newlaurent62** [comment]
lrelease locale/raysession_en.ts -qm locale/raysession_en.qm
lrelease: could not exec '/usr/lib/qt5/bin/lrelease': No such file or directory
make: *** [Makefile:100: locale/raysession_en.qm] Error 1

On Librazik3, Is there a missing dependency ?

**Comment by newlaurent62** [comment]
`sudo apt install qttools5-dev-tools` let me go ahead.

**Comment by newlaurent62** [comment]
Hello,

I'm using it now, Thanks !

Questions : 

- Could it be possible that when selecting one or more clients, the connections between the client ports be highlighted with different colors ?

- Could it be possible that the connections between client ports are set using different colors ? (This could be optional).

Kind Regards,
Laurent

**Comment by Houston4444** [comment]
> Could it be possible that when selecting one or more clients, the connections between the client ports be highlighted with different colors ?

Highlighted yes, why not. With different colors, I think it will disturb the audio/midi difference. 

> Could it be possible that the connections between client ports are set using different colors ?

I don't understand the question. Do you mean: "could you enable user to set a connection color ?", if it this, I'll say no, 1°) for the same reason as the first question, 2°) This kind of feature is not usable for color-blind users, which represents 15% of mens. I 'd prefer work on a more visible think such as horizontal/vertical straight lines.

**Comment by newlaurent62** [comment]
I read your answer, Ok, 

----
Ce que je propose c'est des couleurs sur les connexions pour les différencier. Et que ça puisse être activé à la demande.
----

Other demand: 

Could it be possible that when we select an input or output port on a client box, then press shift, then click on a higher or a lower port, all intermediate ports are selected? 

There could also be two icons on top of client box : one for selecting all input ports and another for selecting output ports.

----
L'idée est d'utiliser la touche shift et de pouvoir sélectionner un port puis un autre port plus bas ou plus haut et que tous les ports intermédiaires soient autoamtiquement sélectionnés.

Ou aussi de disposer d'icones sur la boite client permettant de sélectionner tous les ports d'entrées ou tous les ports de sorties.
----

**Comment by newlaurent62** [comment]
Les demandes ci-dessus n'ont de sens que si on peut sélectionner plusieurs ports et les connecter à un ou plusieurs ports en une opération sinon c'est fastidieux ... Ce que je n'ai pas encore réussit à faire.

**Comment by Houston4444** [comment]
I see. The only interest I can see in multiple selection by the shift key is to highlight the connections of the selected ports, it doesn't seem impossible, although a bit counter-intuitive since all the port actions (connection by drag, or anything in the contextual menu), only concern the port under the mouse cursor.

For fast multiple connections there are already two other solutions:
* right click on a port or portgroup: -> connect
* when connecting by dragging, you can end a connection by right-clicking while holding down the left button, and thus connect in bursts.

___


Je vois. Le seul intérêt que je puisse voir à la sélection multiple par la touche shift c'est la mise en valeurs des connexions des ports sélectionnés, ça paraît pas impossible, bien qu'un peu contre-intuitif puisque toutes les actions de port (connexion par glissé, ou tout ce qu'il y a dans le menu contextuel), ne concernent que le port sous le curseur de la souris.

Pour les connexions multiples rapides il y a déjà deux autres solutions:
* clique droit sur un port ou portgroup: -> connecter
* lors d'une connexion par glissé, tu peux terminer une connexion par un clic droit, tout en maintenant le bouton gauche enfoncé, et ainsi connecter en rafales.

**Comment by newlaurent62** [comment]
Ok cool pour la conexion en rafales !

Ok j'ai vu pour la connexion stéréo en un coup et la mono. Tu pourrais peut-être appliquer le même principe sur plusieurs ports contigus ? Si par exemple, on veut connecter 5 ports (mono ou stéréo) qui se suivent à 5 autres ports sur un autre client ?

**Comment by Houston4444** [comment]
Portgroups are not limited to stereo ! Stereo detection makes only stereo portgroups and user can only make stereo portgroups, but programs can set higher portgroup with JACK metadatas (for 5.1 portgroups for example).

Connect 5 following ports/portgroups to 5 others ports/portgroups would be an absolutely PITA for a very little benefit, without mention the too many odd cases to manage.

_____

Les portgroups ne sont pas limités à la stéréo ! La détection stéréo ne crée que des portgroups stéréo et l'utilisateur ne peut créer que des portgroups stéréo, mais les programmes peuvent définir des portgroups plus élevés avec les métadonnées de JACK (pour les portgroups 5.1 par exemple).

Connecter 5 ports/portgroups consécutifs à 5 autres ports/portgroups serait un travail Gigantesque pour un bénéfice très faible. Sans parler des cas particuliers à gérer.

**Comment by newlaurent62** [comment]
Ok merci pour l'info, dommage ...

**Comment by erwan35** [comment]
Thanks for this cool evolution !

I have noticed some problems with accents on my french librazik. Here is an example :

![accent](https://user-images.githubusercontent.com/4410119/117190793-25991100-ade0-11eb-8a0c-f508c1d78bd6.png)

**Comment by Houston4444** [comment]
@erwan35 
I see. But the problem doesn't comes from RaySession, this is also the case with catia, carla, qjackctl... even jack_lsp forget the accents !
a2j doesn't translate the accents, but if in sysexxer you go to options tab, and set MIDI interface to JACK, you will see "Entrée" correctly written.

But the most important problem here is: A program should never translate JACK port names !!! The jack connections in RS or NSM are memorized with the JACK port names, if a program translate them, sessions shared between users speaking different languages will be broken. What theses programs could use is "pretty-name" JACK metadatas.

**Comment by KannebTo** [comment]
Hi,
I like this patchbay!

I found a little issue with the port display:
![1620550709](https://user-images.githubusercontent.com/24896645/117566386-abee7500-b0b6-11eb-95d9-0a2e66a1582d.png)
Sometimes the grouped port pins are not big enough to hold the text. These port names came from PipeWire. When I use JACK there are just numbered from 1 to 6.

full screen mode:
When I enable full screen mode (double click) and then disable the full screen externally (window manager: i3wm) and then double click 2 times to bring back the rest of the UI, the session frame is collapsed and the enabled menu bar is hidden (I need to disable and enable "Show Menu Bar" again). I also prefer to only change to full screen when double clicking in the background and not on the boxes which I sometimes accidentally do.

responsive design:
When I disable the patchbay the session frame or its child elements are no longer aligned to the left side.
![1620552974](https://user-images.githubusercontent.com/24896645/117567133-ea862e80-b0ba-11eb-8aa6-eaa12d55ee12.png)

**Comment by Houston4444** [comment]
Hi @KannebTo , thanks for this feedback.

port display:
This is not a bug, that is designed this way. The problem is that it is perfectly possible that a portgroup contains ports without a common starting name. If the port size was adapted to the port name, then in that case, the portgroup will be ridiculously little and it would not be comprehensible. 
If you look to port with too long name, you will see that it has no side border.
I see that on your screenshot, it's not pretty, but dynamic port width in some cases would be worse.

full screen mode:
I confirm the bug. I am not surprised because I didn't think to the fact user could set/unset fullscreen from its WM. and set one qwidget fullscreen is something really boring (in reality: RS set window fullscreen and hides all others widgets). There is also a border at left that I didn't achieve to remove in fullscreen mode.
I'll try to resolve this soon.

responsive design: (wrong word here)

I don't really know why, blank should be on the right only, sure, but the idea of this blank is to say to user, don't set RS window maximized without patchbay, it is useless ;)
So this question isn't a priority.

**Comment by KannebTo** [comment]
Works perfectly. Thanks!

**Comment by Houston4444** [comment]
Thanks to everyone here !
The patchbay branch has just been merged to master !
I 'll wait a little for a new release.
