### ISSUE TITLE
ray_control doesn't see a running daemon

### ISSUE THREAD

**Issue by Houston4444** [Houston4444/RaySession#115]
very strange behavior of ray_control starting a daemon with
`ray_control start` and just after unable to find it with `ray_control get_root`. See this topic : https://linuxmusicians.com/viewtopic.php?p=132224#p132224

@lootre

What is your distribution ? what is your raysession's version ?

could you close raysession and run:
`ray_control stop`
`ray_control start`
`ray_control get_root`

and give me the contents of the terminal

can you find a file at path `/tmp/RaySession/multi-daemon.xml`
if so could you give me the permissions of the file with:
`ls -l /tmp/RaySession/multi-daemon.xml`

Thanks a lot

**Comment by lootre** [comment]
Hi !

Thanks for opening this ticket about my issue. I'm glad if I can help you. Also, sorry for the long delayed answer...

Here are the results of the commands:
`toma@toma-studio:~$  ray_control stop
No server started.
toma@toma-studio:~$ ray_control stop~
No server started . So no session to stop~
toma@toma-studio:~$ ray_control start
--- Daemon started at port 16187 ---
toma@toma-studio:~$ ray_control get_root
/home/toma/Ray Sessions`

And also the rights on the file:
`toma@toma-studio:~$  ls -l /tmp/RaySession/multi-daemon.xml
-rw-rw-r-- 1 toma toma 205 May 12 19:26 /tmp/RaySession/multi-daemon.xml`

Thank you for helping !

**Comment by lootre** [comment]
Oh and my distribution is UbuntuStudio 21.04
RaySession version: 0.10.1

**Comment by Houston4444** [comment]
Hi ! Thanks a lot for your reply !

That is strange, everything seems ok for ray_control on your machine.
I really don't understand what happened and I am pretty sure that now you could import an ardour session with the script.
The only error I can suspect is that you works on a computer you never shutdown and you've got an older version of the daemon still running, or something related.

I'd like to ensure the script works correctly, I'd like to add something to run it from the GUI.

Could you please retry the ardour import script ? (NO ROOT !!!)

Cheers
Mathieu

**Comment by lootre** [comment]
Wow, you answer much faster than me !

Lately my music computer is much more often turned off than on, due to a lot of (real) work.

I'll test it again (should manage to do this today) and keep you posted. However, I think of something else: could be the way I "downloaded" the script an issue ? I just copied the script text from [here](https://github.com/Houston4444/RaySession/blob/master/scripts/ardour6_from_external_to_session.sh), pasted it in an empty document, saved it as ardour6_from_external_to_session.sh and made it executable.

Maybe there's a better way ?

**Comment by lootre** [comment]
No idea what happened, but it's working now ! I just started the computer, launched the script and there is it, my Ardour session loaded in RaySession.

Thanks a lot for your help and for this nice piece of software !

**Comment by Houston4444** [comment]
Hi !

> I'll test it again (should manage to do this today) and keep you posted. However, I think of something else: could be the way I "downloaded" the script an issue ? I just copied the script text from here, pasted it in an empty document, saved it as ardour6_from_external_to_session.sh and made it executable.

Humm, it should be fine.

> Thanks a lot for your help and for this nice piece of software !

Thanks, still nice to hear.

I close the issue because I don't think we will achieve to reproduce it.
Cheers
