### ISSUE TITLE
RaySession vs NSM

### ISSUE THREAD

**Issue by diovudau** [Houston4444/RaySession#12]
![Problem](https://imgs.xkcd.com/comics/standards.png)

**Comment by Houston4444** [comment]
trebmuh said all.
Closed.

**Comment by diovudau** [comment]
Two years later: I wanted to document publically that I apologized directly to Houston, and I also changed my attitude.

**Comment by Houston4444** [comment]
Sehr Güt ! 
Apologizes already accepted, and re-accepted.
However, I hope it's not a behavior change only against RaySession and my person.
Send a comic without text as a first communication is something very agressive, especially for someone who just made a free software you didn't like. So I hope to understand you changed your attitude in general ;)
