### ISSUE TITLE
Scaling regression

### ISSUE THREAD

**Issue by theGreatWhiteShark** [Houston4444/RaySession#120]
Window manager: i3 version 4.16.1 (2019-01-27)
Resolution: 1920x1080

---

After updating RaySession from **v.0.10.1**

![raysession_0 10 1](https://user-images.githubusercontent.com/14164547/121243132-a6df3a00-c89d-11eb-9b01-5dd893139c27.png)

to **v.1.0.0-alpha.1**

![raysession_1 0 0 alpha](https://user-images.githubusercontent.com/14164547/121243176-b5c5ec80-c89d-11eb-9f21-46286473da18.png)

most of the icons and some newly introduce text are not properly shown. The problem persists on resizing the left column in RaySession.

This might be due to the tiling window manager I use.

**Comment by Houston4444** [comment]
Hi.
The regression is to "update" to v.1.0.0-alpha.1. This is a very old version, sorry.

**Comment by theGreatWhiteShark** [comment]
Ah, I see. When seeing the tag v1.0.0-alpha.1 in the command line I thought you were starting to prepare a new major release. Forgot to check the date in the log. Sorry.
