### ISSUE TITLE
version number hadn't be changed in RS 0.5.5

### ISSUE THREAD

**Issue by sub26nico** [Houston4444/RaySession#13]
In 'Help' menu, 'about Ray session', the version number says 0.5.4 in 0.5.5 version, 
Maybe  you forgot to change it ?

**Comment by trebmuh** [comment]
It looks correct since it's been done after the 0.5.5 release [here](https://github.com/Houston4444/RaySession/commit/08cae5e975ffc64691f20f6d963c0e4cb5a605af).

**Comment by sub26nico** [comment]
Ok, so I close here
