### ISSUE TITLE
capability to know other clients states

### ISSUE THREAD

**Issue by Houston4444** [Houston4444/RaySession#134]
This discussion is in french, sorry for the others.

Ajouter la possibilité pour un client d'obtenir les informations d'état des autres clients.
@jean-emmanuel

**Comment by jean-emmanuel** [comment]
J'ai fais un petit test de mon côté et finalement je ne suis pas sûr qu'il faille que ce soit  géré au niveau client nsm dans mon cas : le processus qui a besoin de ces infos va être amener à se relancer tout seul assez souvent (quand on modifie les fichiers de conduites pour écrire les morceaux), ce que raysession interprète comme l'arrivée d'un nouveau client à chaque fois (je garde pourtant le même pid), c'est assez polluant dans la session. La solution/hack actuelle (se faire passer pour une instance de gui) est assez pratique en ce qu'elle permet de sonder l'état de raysession sans avoir à se conformer au comportement attendu d'un client.

**Comment by Houston4444** [comment]
j'ai rajouté côté serveur le message` /nsm/server/monitor_reset` , qui renvoie les états des clients par `/nsm/client/monitor/client_state` .

**Comment by jean-emmanuel** [comment]
Merci !

**Comment by Houston4444** [comment]
Je suis en train de revoir le jackpatch pour diverses raisons, il va utiliser la capability ':monitor:'. Et là je me rends compte qu'il y a une erreur, tous les évènements de clients sont bien nommés :

started
joined
ready
saved
stopped_by_server
stopped_by_itself
removed
open_error
save_error
start_request
save_request
stop_request

Excepté 'stopped_by_server' et 'stopped_by_itself' qui eux sont nommés 'client_stopped_by_server', et 'client_stopped_by_itself'.
Je renomme donc ces évènements comme il se doit (sur une branche de dev, ça s'appliquera plus tard au master).

Par ailleurs, je vais avoir besoin du nom de client JACK que le serveur envoie au client. Il est possible que je change donc:

**Comment by jean-emmanuel** [comment]
Yes, j'avais remarqué cette incohérence mais oublié de te le dire. L'autre changement semble peu risqué en effet.

**Comment by grammoboy2** [comment]
@jean-emmanuel 

I'm curious, do you have a particular example use case? How do you use this feature?

Do you want to know the states of some specific NSM clients, or all of them? 

Can't the :broadcast: functionality help you here?

**Comment by jean-emmanuel** [comment]
Hi, I haven't got time to explain it in detail but basically I use [this](https://jean-emmanuel.github.io/mentat/) as a hub to manage and synchronize the state of all the softwares in a [big setup](https://github.com/Houston4444/RaySession/assets/5261671/b62794d5-50e4-4a97-a6dc-109910734a0c) and to do it properly I need to know when a software is ready or not. In the end all of [this](https://github.com/PlagiatBros/PlagiatSetupII) drives the live setup of a weird french [hip-hop](https://plagiat.org/clips.html) band.

**Comment by grammoboy2** [comment]
Thanks. Impressive setup. 

Do you need to know the states only at start of the session (when session is loaded) or also on other moments? 

Is the setup fully automatic, or are manual operations  involved to start scripts at certain moments? 

You let one application announce to the NSM server with the :monitor: capability?

**Comment by jean-emmanuel** [comment]
Only the hub/conductor software announces as :monitor:, it needs state updates at any time because when a software is ready/restarted it must send the values of all its parameters so that the conductor remains the "source of truth".

> Is the setup fully automatic, or are manual operations involved to start scripts at certain moments?

Starting the setup is almost fully automated, we only start the hub manually after everything else is launched (although it could be automatic as well). After that many things can be automated but the idea is to use physical controllers to jump from a scene to another so that the whole setup follows the musical performers throughout the show instead of the opposite.

**Comment by grammoboy2** [comment]
I see. I just wonder if the hub/conductor should be a NSM client. Isn't the hub/conductor more comparable with some sort of NSM GUI with specific functionality? At least the tool seems to 'conduct' a whole session. A NSM GUI already knows the states of the clients, such conductor tool might be able to use the same mechanism to get the states of the clients, without being a NSM client itself and so without being part of the session itself.

**Comment by jean-emmanuel** [comment]
I went for a separation of concerns and decided to not make it a client but it could be one. In this setup, nsm/raysession is responsible for running the apps, loading their initial states (files) and providing a proper patchbay, then the dynamic state of things is handled by the conductor.

**Comment by grammoboy2** [comment]
Makes sense I think. In fact I tend to think that you don't need a :monitor: capability on the NSM client API side, to make such (specific) setup work, given the fact that such mechanism already exists for NSM GUI's more or less.
