### ISSUE TITLE
[Feature] Scroll when dragging a box or a wire and reaching a patchbay border 

### ISSUE THREAD

**Issue by orlammd** [Houston4444/RaySession#135]
When moving a box, nothing happens when the mouse reaches the patchbay border. As a result, one must drag and drop the box he wants to move several times, each time having the risk to disturb the alignment of the boxes in the neighbourhood. It would be cool that reaching a border woul trigger a scroll so that you can move the box easily.

The same goes for the wire, when you want to plug two boxes quite far away one from the other.

**Comment by Houston4444** [comment]
You can drag the scene while pressing middle mouse button (wheel button).
Ahah, I didn't know that but it works even if you are making a connection.
Is it ok this way ?

**Comment by Houston4444** [comment]
While moving a box, you can use the mouse wheel directly. With ALT pressed if you want to move horizontally.

**Comment by orlammd** [comment]
Yes, that second option is OK, cause it allows one to extend the zone in which you can drop the boxes one moves.
Thanks.
