### ISSUE TITLE
[Feature] Client-id or name-based filtering

### ISSUE THREAD

**Issue by orlammd** [Houston4444/RaySession#136]
As well as it's possible to filter clients visibility in the patchbay by MIDI or Audio type, it would be nice to be able to filter by client-id or name, if possible with syntax allowing the use of "*".

**Comment by Houston4444** [comment]
That is a complex thing. Not complex alone, but regarding other features.
Audio or Midi filter gives another view, that means that if you show only Midi ports, you move boxes, you restore all ports view, positions will be restored as they were before filtering.

I also think to canvas zones, which does not exist yet, but are planned. I don't know exactly how I will do that, but I want zones to be wrapables. I think you understand the problem ;)

Something easier would be something as 'highlight boxes with pattern', just painting a red rectangle around boxes, for example.

**Comment by orlammd** [comment]
Yep, I do understand. Maybe one thing possible would something like "emballer" every client which doesn't match a filter, and expand the others?
The aim would be to be able to have a quick look at a signal flow.

**Comment by Houston4444** [comment]
idea:
filter could be a lineEdit at top toolbar (at left of zoom slider).
We could opacify groups not matching with the pattern (we also should opacify connections not related to any matching group).

for example, I just tested to make box opacity at 0.2, and this is how it looks:

![screenshot_box_opacity](https://user-images.githubusercontent.com/3808689/142398098-20b969e5-1ad5-4fe4-adc5-bc4d0d3e82e5.png)

I don't why titles aren't opaque, but I didn't search.

**Comment by orlammd** [comment]
Looks good to me!

**Comment by Houston4444** [comment]
news of patchbay_filter branch.
Now, with Ctrl+F, a filter bar appears at the bottom, you can type directly your string, and navigate through matching boxes with arrow keys.

I think it looks very nice, rest just to make a slider to adjust hidden opacity, and an action in patchbay menu.

**Comment by orlammd** [comment]
Works fine! Great!

**Comment by Houston4444** [comment]
Merged to master some days ago.
