### ISSUE TITLE
Not launching on Ubuntu 16.04 (Mate)

### ISSUE THREAD

**Issue by erwan35** [Houston4444/RaySession#14]
Hello,

I have tried RaySession on Ubuntu 16.04 (Mate). No problem to compile it but an issue is occuring when the software is being run.

`erwan@menhir:~/RaySession$ src/raysession 
Traceback (most recent call last):
  File "src/raysession", line 2077, in <module>
    ray_daemon = RayDaemon()
  File "src/raysession", line 1980, in __init__
    self.process.errorOccurred.connect(self.errorInProcess)
AttributeError: 'QProcess' object has no attribute 'errorOccurred'`

As discussed on IRC, it seems to be related to a qt function that was introduced in qt5.6 and that is not available in the qt release included in Ubuntu 16.04.

Cheers
Erwan

**Comment by Houston4444** [comment]
Ok. I just tried something to get a workaround for this.
Please update and try again.
Even if it works, you won't be able to know if a command launched by RaySession has not been started for various reasons.

**Comment by erwan35** [comment]
Hello and thanks for the quick fix !
I can launch it now.

Cheers
Erwan
