### ISSUE TITLE
Places where drawLine can be called with floats instead of ints causing a crash

### ISSUE THREAD

**Issue by dsheeler** [Houston4444/RaySession#140]
I've hit the first of these in use, lately, but I don't know when the second one happns:

https://github.com/Houston4444/RaySession/blob/5be1c1159ca5ba04491150b14fd9e3c0fd7f19d1/src/gui/patchcanvas/canvasport.py#L907

https://github.com/Houston4444/RaySession/blob/5be1c1159ca5ba04491150b14fd9e3c0fd7f19d1/src/gui/patchcanvas/canvasbox.py#L1666

**Comment by Houston4444** [comment]
ahh, that is due to python3.10.
Ok, I fix it and I draft a new release (there was already another important bug).

**Comment by Houston4444** [comment]
In the second one, it is impossible to have one of theses four values not being a float.

**Comment by dsheeler** [comment]
> In the second one, it is impossible to have one of theses four values not being a float.

Is that supported though, in the drawLine interface? Seems like they all have to be ints?

**Comment by dsheeler** [comment]
Oh, if they're all floats that works? I just looked at your fix... I thought making them all ints was necessary.

**Comment by dsheeler** [comment]
So I just confirmed the crash still happens after pulling the most recent code.  Here's the error:

```
Traceback (most recent call last):
  File "/usr/share/raysession/src/gui/patchcanvas/canvasport.py", line 907, in paint
    painter.drawLine(
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by dsheeler** [comment]
I guess you could use two QPointFs?

**Comment by Houston4444** [comment]
Oh, you are right, thanks. It should be fixed now, I used QPointFs of course

**Comment by Houston4444** [comment]
arff, I was hoping that the daemon could not be affected because there is few Qt and no floats... but a division creates a float.

It should be fixed with the last commit.
Thanks

**Comment by Stazed** [comment]
Yes, it is working now. 
Thanks.
