### ISSUE TITLE
Tray menu appears and disappears immediately on right click

### ISSUE THREAD

**Issue by maxigaz** [Houston4444/RaySession#146]
When I right click on the tray icon, the tray menu appears and disappears immediately, and the main window of RaySession is hidden or shown (as if I clicked on the tray icon with the left mouse button).

The issue doesn't happen when Carla's window is also open and in focus.

OS: Arch Linux with i3-gaps and Polybar
RaySession: compiled from master (through the AUR package raysession-git)
Qt version: 5.15.4

**Comment by Houston4444** [comment]
Hi.

This is very strange. I don't think carla provides a systray icon, so I really can't see the possible link (that doesn't means I don't believe you ;)).

Do you know any other Qt apps providing a systray menu and where this bug doesn't happens ?

**Comment by maxigaz** [comment]
> I don't think carla provides a systray icon, so I really can't see the possible link

After some further testing, the bug doesn't happen when any application launched by RaySession is in focus, be it Carla, Ardour, or Qtractor. Otherwise, I can always reproduce it.

> Do you know any other Qt apps providing a systray menu and where this bug doesn't happens ?

No. I have Strawberry, but it doesn't affect RaySession in any way.

**Comment by Houston4444** [comment]
What a very strange thing.

Can you try if it still happens when the daemon is launched before the session. Simply:
* start raysession
* open a session
* close the RS window (and keep daemon running)
* restart raysession
* test

**Comment by maxigaz** [comment]
> What a very strange thing.
> 
> Can you try if it still happens when the daemon is launched before the session. Simply:
> 
>     * start raysession
> 
>     * open a session
> 
>     * close the RS window (and keep daemon running)
> 
>     * restart raysession
> 
>     * test

Same results.

**Comment by crshrprt** [comment]
I had the same issue. It seems to have been fixed with https://github.com/Houston4444/RaySession/commit/3e2a1b53fbf4f19bd00183e0624797a0c1413976.

**Comment by Houston4444** [comment]
News go fast ;)
