### ISSUE TITLE
Invalid names displayed for ports in porgroups with num index over 10

### ISSUE THREAD

**Issue by blufor** [Houston4444/RaySession#147]
I'm happy with this awesome tool, however there one thing that bugs me quite a lot. I have an USB audio interface with 24i/24o and the way it presents the interfaces indexed over 10 is inconsistent:

![image](https://user-images.githubusercontent.com/2767365/196063607-448a2921-dcfe-4be2-87c6-357c94f70161.png)

When the ports are split in monos, they correspond to the device names properly, so it's probably just an UI rendering issue (I've been looking a bit at the code and the parsing seems correct to me on that side)

BTW I've tested that this is also valid for Patchance

**Comment by Houston4444** [comment]
hi. Thanks for the report.
I just fixed it with https://github.com/Houston4444/HoustonPatchbay/commit/3dc037ce02eab4cee420fe0ca8a835dfb92d2f95.
Please test !

> BTW I've tested that this is also valid for Patchance

Next time you will know, if a bug is valid for both RaySession and Patchance, then the good place to report a bug is https://github.com/Houston4444/HoustonPatchbay/issues .
This is really not strong of course.

**Comment by blufor** [comment]
Works perfectly now, thx a lot!
