### ISSUE TITLE
NSM Environment varibles not being saved.

### ISSUE THREAD

**Issue by Stazed** [Houston4444/RaySession#148]
Setting environment variables from application icon /Properties/NSM/Environment variables, gets cleared when session is closed and restarted. Pressing the "Save Changes" button in the Properties/NSM dialog does not save, nor saving whole session.

RaySession version 13.0.

**Comment by Houston4444** [comment]
Ahah, sorry for that, as crazy as it sounds, it was just forgotten.
Fixed with last commit : https://github.com/Houston4444/RaySession/commit/d5fb6a6bf09d79c9a54b5fe28207e2e191387620

**Comment by Stazed** [comment]
Thanks for the quick response!!!
