### ISSUE TITLE
Session fails to load

### ISSUE THREAD

**Issue by dsheeler** [Houston4444/RaySession#149]
I have been getting a crash on this line: https://github.com/Houston4444/RaySession/blob/d5fb6a6bf09d79c9a54b5fe28207e2e191387620/src/daemon/bookmarker.py#L359 because somehow, `shortcuts` is a string instead of a list. To get past the crash, I tested for `shortcuts` being a string and just didn't do the append. I don't know what should be done!

**Comment by Houston4444** [comment]
> the application continues to run, but the session doesn't load:

It is still a big problem.

[last commit](https://github.com/Houston4444/RaySession/commit/bbd71f2890cf86dd514e473a6be6c00820dac1d4) should fix the problem, I hope. Which versions of python and Qt are you using ?

**Comment by dsheeler** [comment]
I'll try with the new commit, but it looks good to me.

I'm on arch linux and Python is 3.10.8
and I use this package for pyqt5:
Qt python-pyqt5 5.15.7-2

**Comment by Houston4444** [comment]
I suspect that you did not clone the repository with --recurse-submodules argument. No ?

**Comment by dsheeler** [comment]
That was the issue.  Thank you! 

And now I can say the commit works for me, too!  Thank you for the quick response and fix!
