### ISSUE TITLE
Hide pavucontrol from patchbay

### ISSUE THREAD

**Issue by ericek111** [Houston4444/RaySession#156]
It would be nice if we could filter out nodes based on some parameters like client name and such. I like to use pavucontrol to manage volumes, but it pollutes the patchbay significantly.

**EDIT:** My apologies, perhaps this is better suited for https://github.com/Houston4444/HoustonPatchbay

_P. S.: I just learned about your project and OMG it is EXACTLY what I needed and missed for years! Helvum can be extremely cumbersome. This app is perfect. Thank you very much for making it, it makes using Linux even more fun._

**Comment by ericek111** [comment]
Yeah, sorry, I should've researched a bit more before opening an issue. This is almost a duplicate of https://github.com/Houston4444/HoustonPatchbay/issues/3

**Comment by Houston4444** [comment]
> _P. S.: I just learned about your project and OMG it is EXACTLY what I needed and missed for years!_

Thanks. Quite a shame, RaySession also exists for years.

>it makes using Linux even more fun.

This is exactly its goal !
