### ISSUE TITLE
Program considered stopped after doing execvp()

### ISSUE THREAD

**Issue by jpcima** [Houston4444/RaySession#16]
Hello. I am the author of [adljack](https://github.com/jpcima/adljack/).

For context, this program uses curses for UI and can be built for either ncurses (consoles) or pdcurses (X11 window). The pdcurses variant works and does not require anything special. The trouble comes with the terminal version.

For the sake of NON session manager, I implemented [this code](https://github.com/jpcima/adljack/blob/master/sources/jackmain.cc#L223). What it does is this: if it runs under session management, the program will reexecute itself into a xterm program or similar, in order to have a visible user interface.

NON is perfectly happy with this, but RaySession is not. It must be the fact of doing `execvp`, which must confuse the process management.

**Comment by Houston4444** [comment]
Hi.
That's normal, Ray Session doesn't accepts clients which are not launched by himself.
More exactly, if the process launched by Ray Session has been stopped (that seems to be the case here when adljack re-execute itself), then the new client registered can't be considered as coming from RaySession and is ignored.

Because of the ray-daemon design, it would be too hard to accept clients not launched by himself.

I can suggest three solutions:
* modify your code to have a child process that doesn't stop the first process launched. 
* make another start script (for example called adljack_nsm) that starts directly adljack in terminal. I could add an application template to RaySession that loads directly this script.
* (Concerns me, maybe the best solution) make RaySession capable to run any process in a terminal, with the way you done it.

Did you try (or have returns) of environment variable XDG_CURRENT_DESKTOP ? I mean, are you sure that under Unity, Cinammon or E17, lxqt, the good one terminal is launched ?

**Comment by jpcima** [comment]
Does Ray Session track the child processes by their pid? as far as I known, `exec` is not going to change the pid, nor is it going to instantiate a new process. As the man page puts it, it's a "replacement of  the current process image with a new process image".

As such, I am not too surprised that this would work in Non session manager.
I can see if I can adopt one of these solutions in adljack.

> Did you try (or have returns) of environment variable XDG_CURRENT_DESKTOP

Yes I'm already doing this in code, just few lines above the function which I showed.

**Comment by Houston4444** [comment]
Hi. I just tried adljack, sorry.

> NON is perfectly happy with this
I tested it under non-session-manager, I won't say that NON is perfectly happy with this. The first client launched status stays "launch", a second one appears and is the good one client. But when you reopen session, non thinks he has 2 clients to launch, and the first one launch another one client, that makes 3 clients for no reason.

Forget my solutions, the first process is still running, but nor in Ray Session or NSM, the client registration is considered as coming from him, that is the problem !

This certainly comes from first infos sended by adljack to NSM via OSC server.

**Comment by jpcima** [comment]
> the client registration is considered as coming from him, that is the problem

Thanks but I'd like to know: what has given you this information?  There is a relevant log output to look at?

**Comment by Houston4444** [comment]
> what has given you this information?

Hum, that's just that I know how Ray Session and NSM works. 

So, your error is to send an absolute path as executable to NSM. probably in jackmain.cc , line 275: 
`nsm_send_announce(nsm.get(), "ADLjack", "", argv[0]);`

Personnaly, I just decide for raysession to allow programs to send an absolute executable path, and just consider its basename (this is not the first time that this error append). So if you update raysession, you will see that adljack is working well.

find a way to send basename of argv[0] and it will works in NSM too.

**Comment by jpcima** [comment]
Oh! It's nice of you of having looked into my problem. I have not focused on this and been working on few other things.

I send argv[0] in the announce because this is done in the code sample which is given by nonlib/nsm.h.
See yourself. The file header has an example code to use. https://git.tuxfamily.org/non/non.git/tree/nonlib/nsm.h

This is the relevant line `nsm_send_announce( nsm, "FOO", "", argv[0] );`.

**Comment by Houston4444** [comment]
> I send argv[0] in the announce because this is done in the code sample which is given by nonlib/nsm.h.

So that's why this is not the first time that I see this error.

**Comment by jpcima** [comment]
I have announced with the good name now, unfortunately I still have no luck with Ray Session. This has not been enough to fix it.
I am still having the program showing as stopped soon after it's launched, and staying in the state of waiting for its `open` message.

**Comment by Houston4444** [comment]
that's strange, it was working well here !

**Comment by jpcima** [comment]
Oh god I know!!! It's the Mate terminal.
It's a single instance program and it reuses the existing terminal process. The process is going to exit right away...

**Comment by jpcima** [comment]
It works... I close this issue now.

**Comment by Houston4444** [comment]
If you want you can improve it a little for konsole (kde).
It's nicer if program is launched as this:
`konsole --hide-menubar --hide-tabbar -e myprogram`

it hides unneeded tools here, more it prevents user to use another tab in konsole that would be killed by stopping the program via NSM or RaySession.

**Comment by jpcima** [comment]
Good. I will do the same kind of things to optimize for all terminals, and I will check no kind of process communication is going to interfere in the process creation.

**Comment by grammoboy2** [comment]
Old issue, but it looks like adljack is announcing with the wrong pid

real pid 31896 vs announced pid 31900, for example.
