### ISSUE TITLE
Connection graph gets screen size wrong

### ISSUE THREAD

**Issue by strk** [Houston4444/RaySession#160]
I have two monitors, one is wide and things look fine there, when I move raysession to the other monitor, which isn't wide, the element do not reorganize correctly, as if the engine thinks the screen is wider than it is.

See screenshot:

![screen](https://user-images.githubusercontent.com/289678/222516844-ef392c2d-1898-4093-b723-df30eaf72896.jpg)

**Comment by Houston4444** [comment]
Ok, this has probably no link with RaySession itself, I suppose the bug happens with all Qt programs, I suspect it comes from your window manager. Which Desktop Environment do you use ?

**Comment by strk** [comment]
I'm runnign LXQt and yes, it does happen with some other programs too (like MuseScore3)

**Comment by Houston4444** [comment]
Ok, This is a LxQt bug !

**Comment by strk** [comment]
I'm having the same problem with i3, should this issue be reopened ?

My screens layout: xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1280x0 --rotate normal --output HDMI-1 --mode 1280x1024 --pos 0x0 --rotate normal

What you see in the screenshot is on the HDMI-1 screen

![image](https://user-images.githubusercontent.com/289678/225252745-79674bcd-4df4-438b-9f8f-6a06568e6eaa.png)

**Comment by Houston4444** [comment]
I really suspect it is more a problem related with i3, or maybe with Qt

**Comment by strk** [comment]
Not related to i3, here it's happening under Mate on a Debian 11. Note that Mate is GTK based, not QT.

![image](https://user-images.githubusercontent.com/289678/225540332-ac679017-ea82-41a4-9032-ea295a0c42df.png)

In this case this is a single monitor setup.

Are you suggesting it's QT as used by RaySession that's bogus ? Or am I having the wrong expectation as to how the patchbay should behave ?

**Comment by Houston4444** [comment]
It is not related to the patchbay, it concerns the full window. I am surprised you see this with Mate, I already tested it with Mate and I have two monitors too, without this problem. I'll retest it. 

Ahhh, or Maybe you think patchbay should auto adapt it's zoom to the visible space? In this case, the answer is short, No, it should not, some users have a very large scene with many boxes, adapt the zoom would result in something not readable.

**Comment by strk** [comment]
Ah ok, yes, I was expecting it to auto adapt, as I saw it automatically zooming out when boxes are dragged past the borders...
