### ISSUE TITLE
Node/Client boxes position not restored correctly on first load

### ISSUE THREAD

**Issue by crshrprt** [Houston4444/RaySession#165]
Not sure it's a RaySession or HoustonPatchbay bug. Anyway, I built the latest RaySession from git and now when opening a session for the first time, after starting JACK, the node/clients positions aren't restored correctly. If i check or uncheck "Canvas Options > Provide ALSA Midi ports" the node clients move to their correct/last saved position.

Here's a video of the bug:

https://user-images.githubusercontent.com/114294020/228217221-67bf802f-70db-412a-84d4-6375518c8c98.mp4

**Comment by Houston4444** [comment]
Thanks for this complete report.
I've fixed the bug , it was in HoustonPatchbay, but you could not know.
I saw this two days ago in my dev branch, but I forgot to update HoustonPatchbay in the master branch.

It should be now fixed.
