### ISSUE TITLE
Problème de lancement de ray session

### ISSUE THREAD

**Issue by trebmuh** [Houston4444/RaySession#17]
Si tu peux y jeter un œil : http://linuxmao.org/forumthread86363

**Comment by sub26nico** [comment]
le problème semble 'Raysolu' :-)

**Comment by Houston4444** [comment]
ah oui t'as rayson !

**Comment by trebmuh** [comment]
Bon, bah si tout le monde est d'accord, c'est rayconfortant !

**Comment by Houston4444** [comment]
bon ça suffit les calembourgs à deux francs, on arrayte.

**Comment by trebmuh** [comment]
Oh ba si on a plus le droit ici, je retourne faire des jeux-de-mots aux arbres dans ma foray.
:smile:

**Comment by sub26nico** [comment]
pourtant, ça doit être ray-confortant un problème ray-solu ! 
Une ray-compense di-ray-je !
