### ISSUE TITLE
Improvement: save zoom state in the session

### ISSUE THREAD

**Issue by ycollet** [Houston4444/RaySession#170]
When I open a session, the zoom is automatically set to 100%
Can it be possible to save the state of the zoom in the session ?

**Comment by Houston4444** [comment]
mmh, not so easily, this is designed to have a custom default zoom (in canvas options), but not per session zoom. As user, I think I would not want this, and I don't really see the interest TBH, zoom is very fastly changed.

Tip:
You can right click on zoom slider to reset to default, or double click to fit the view to contents.

**Comment by ycollet** [comment]
Or maybe something like an automatic "zoom fit" at startup, to avoid zooming manually to get the whole patch in the screen ?

**Comment by Houston4444** [comment]
Or maybe something like an automatic "zoom fit" at startup, to avoid zooming manually to get the whole patch in the screen ?

The problem with a such feature is that labels could be unreadable if they are too small, this would be an accessibility issue.
