### ISSUE TITLE
Build fails, file missing

### ISSUE THREAD

**Issue by crshrprt** [Houston4444/RaySession#178]
Trying to build latest RaySession fails because of a missing file, `systray_management.py`, not existent anymore:
https://github.com/Houston4444/RaySession/blob/c3d85f05eafba70ac88bff09269ca85b3252758c/Makefile#L93

**Comment by Houston4444** [comment]
thanks for the report. Fixed by https://github.com/Houston4444/RaySession/commit/517e865964ca52106863d3fedd49e9dabda8c1f0 .
