### ISSUE TITLE
Python 3.11 removes inspect.getargspec

### ISSUE THREAD

**Issue by jold42** [Houston4444/RaySession#179]
Apparently deprecated in favour of 
inspect.signature
Not sure if this is the only issue but critical to running with python 3.11 
Hope this is an easy fix. RaySession is just too useful

**Comment by Houston4444** [comment]
> RaySession is just too useful

Nice to ear !

This comes from python3-liblo, as said in https://github.com/Houston4444/RaySession/blob/master/INSTALL.md#running, please use the liblo lib from here : https://github.com/gesellkammer/pyliblo3 .
