### ISSUE TITLE
Feature request: display labels in Messages panel

### ISSUE THREAD

**Issue by mxmilkiib** [Houston4444/RaySession#18]
It would be handy to tell which ray-proxy (or whatever) instance an event is related to if there is more than one in use.

**Comment by Houston4444** [comment]
Hi. I didn't understand, i was believing you were talking about terminal messages.
Are you talking about messages dock ?
Yes you're right, I could review these messages, for the moment they are globally the sames as in NSM.
This will be in the next version.
