### ISSUE TITLE
Remember client node long/tall layout?

### ISSUE THREAD

**Issue by mxmilkiib** [Houston4444/RaySession#199]
The "long" or "tall" layouts aren't remembered on reloading a session. Unless I'm doing something wrong! :)

**Comment by Houston4444** [comment]
humm, here it seems to work, so, I don't know what I can say...

**Comment by mxmilkiib** [comment]
Are there any debugging steps I can take? I'm using -git from the AUR, naturally.

**Comment by Houston4444** [comment]
Found it ! Fixed !
