### ISSUE TITLE
Numéro de version

### ISSUE THREAD

**Issue by trebmuh** [Houston4444/RaySession#2]
_Aide -> À propos de Ray Session_ dit que c'est une version 0.4.0 alors qu'il semble que ce soit la 0.4.1

Il semble qu'[ici aussi](https://github.com/Houston4444/RaySession/blob/master/session_templates/withJACKPATCH/raysession.xml), il soit mentionné 0.4.0 au lieu de 0.4.1

**Comment by Houston4444** [comment]
Effectivement, j'avais oublié de modifier le numéro de version avant de publier la 0.4.1.
Le code source est déjà en 0.4.2, donc pour la suivante y aura pas d'erreur à priori.

**Comment by trebmuh** [comment]
👍
