### ISSUE TITLE
Middle-click dragging; once cursor gets near edge, movement direction reverses

### ISSUE THREAD

**Issue by mxmilkiib** [Houston4444/RaySession#200]
[raysession-bug-middle_drag_direction-2023-09-19_06.04.49.webm](https://github.com/Houston4444/RaySession/assets/108225/7aba5ae6-3602-4f77-b3af-d01d2f42fd5f)

This is without elastic canvas or navigate on borders enabled.

**Comment by Houston4444** [comment]
Ok, thanks for the report.
One more bug happening with python3.11 and not with python3.9. I will take a look.

**Comment by Houston4444** [comment]
No, I was wrong, the python version is not in question. In fact, there are two bugs:
1 ) borders navigation is not restored at startup (if False, default is True)
2 ) Middle click should not activate borders navigation

The first one is easily fixed, the second one is more complex, I am checking this.

**Comment by Houston4444** [comment]
Ok, it should be fixed now !

**Comment by mxmilkiib** [comment]
I don't think it's fixed. I think this is #201 related.

**Comment by mxmilkiib** [comment]
So this is fixed now!
