### ISSUE TITLE
"Navigate on borders" is on even when the option is unchecked

### ISSUE THREAD

**Issue by mxmilkiib** [Houston4444/RaySession#201]
raysession-git-r1945.c5bdb04

I tried checking it then unchecking again, but the canvas viewport moves around when the cursor goes near the canvas edges.

**Comment by Houston4444** [comment]
mmmh, very very strange, I can't reproduce this. You mean, even if you check and uncheck the option, without restarting RaySession, navigate on borders persists ?

is your Qt version 5.15.2 ?

I suppose you are sure HoustonPatchbay submodule is up to date.
I really can't see what is going on.

**Comment by mxmilkiib** [comment]
5.15.10 I think? Just an up-to-date Arch install.

The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=raysession-git) that creates the comrpessed package archive.

**Comment by Houston4444** [comment]
> The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=raysession-git) that creates the comrpessed package archive.

I suggest to make the package depend on python-pyalsa too, to enable directly ALSA Midi ports.

But for the bug, I still have no idea.

**Comment by Houston4444** [comment]
In my humble opinion, you have a serious config problem or maybe you are not launching the version you think, or something else on your side. I tried yesterday to start it in my (broken) Manjaro, without this issue.

What is very very strange, is that, the "navigate on borders" option had an issue (never off at start), but AFAICT this issue (check/uncheck does nothing) never existed.

I let it open in case someone else has a similar issue.

**Comment by mxmilkiib** [comment]
Does "navigate on borders" mean "move the viewport when one is dragging a client around"? That's what the behaviour is now.

Because the behaviour I was getting previously was "move mouse cursor to edge of viewport and viewport moves in that way", which now isn't the case.

**Comment by Houston4444** [comment]
> Does "navigate on borders" mean "move the viewport when one is dragging a client around"? That's what the behaviour is now.

Yes, move the viewport when dragging a box, making a connection, or just selecting boxes. It needs at least one click (double click is possible for connecting ports without keep down the mouse button, for easier use with touch-pad).
