### ISSUE TITLE
Hidden GUI state is not remembered in the session

### ISSUE THREAD

**Issue by crshrprt** [Houston4444/RaySession#203]
raysession-git-r061176f29b6ab0e71e75634985629ecc90c2aeff

Hidden GUI states are not remembered anymore: Clients like Carla and jack_mixer always start with their GUI shown, despite the session being saved with their GUI hidden. Option "remember optional GUI states" is enabled.

**Comment by Houston4444** [comment]
Fixed !
Thaks for the report.
