### ISSUE TITLE
Défilement horizontal (Alt+scroll vs Shift+scroll)

### ISSUE THREAD

**Issue by jean-emmanuel** [Houston4444/RaySession#204]
Il me semble que la plupart des logiciels utilisent shift+scroll pour le défilement horizontal (quelques examples: ardour, libreoffice, gimp, inkscape... en fait je ne trouve pas de contre example), or dans raycanvas c'est alt+scroll, c'est un peu déroutant. Est-ce qu'il y a une raison particulière que j'aurais manquée ? 

It seems to me that most software uses shift+scroll for horizontal scrolling (some examples: ardour, libreoffice, gimp, inkscape... in fact I can't find a counter example), but in Raycanvas it's alt+scroll, it's a bit confusing. Is there a particular reason I missed?

**Comment by Houston4444** [comment]
C'est pas bien grave mais j'aime autant qu'on parle anglais ici pour les choses qui concernent tous les utilisateurs.

In fact, this is a Qt choice, I made nothing for that. QJackCtl, Carla, Kdenlive works this way. Qtractor has made the choice to enable Alt OR shift for horizontal scrolling. I think this is the good choice. It's very surprising that I never realized it !

I will take a look.

**Comment by Houston4444** [comment]
Ok that is done, It was not easy but it seems to work.
Please confirm.

**Comment by jean-emmanuel** [comment]
Yep, it works now, thanks :)
