### ISSUE TITLE
desktop key

### ISSUE THREAD

**Issue by grammoboy2** [Houston4444/RaySession#206]
Wouldn't it much better if there was just one key for the NSM Desktop file entry? One key is simple stupid. Two keys is also a lot for such a niche use case as NSM is. Only Carla needs multiple keys it seems, which I'm not sure about either. What's your opinion @Houston4444? Are you sure two keys are really needed and if so why exactly? 

https://linuxmusicians.com/viewtopic.php?t=25615

**Comment by Houston4444** [comment]
Two keys is not a problem. I see use cases where X-Nsm-Exec can be useful (if the executable is different for NSM run, without having to add more .desktop files).
However, I hadn't seen the messages of this github thread  (strange, I participate), so, indeed, X-Nsm-Exec is not implemented in RaySession, but it could of course.

**Comment by Houston4444** [comment]
> Two keys is also a lot for such a niche use case as NSM is.

I still believe that it will not remain a niche use, I don't think there is any interest to use GNU/Linux audio programs without RS when user know how it works, except (maybe) for very little projects.

**Comment by grammoboy2** [comment]
Yes, I think X-Nsm-Exec is actually the only key that is really needed, but I could be wrong.

The question is: are two keys really needed. If one covers all, that's obviously the better option. 

I hoped you could explain me convincingly that two keys are a real must and why only X-Nsm-Exec is not enough.

**Comment by grammoboy2** [comment]
I saw someone even commented on the nsmd fork github issue. Hm sounds like that guy knows something about it, ok then I rest my case.
