### ISSUE TITLE
ray-network binary?

### ISSUE THREAD

**Issue by trebmuh** [Houston4444/RaySession#21]
Is a "ray-network" binary expected to be installed?

**Comment by Houston4444** [comment]
No, that's not needed. ray-daemon adds the RaySession/src at begginning of the $PATH, so it will always be found. And there is no reason to start ray-network outside of ray-daemon.

**Comment by trebmuh** [comment]
This is confusing with what's describe on [the release information](https://github.com/Houston4444/RaySession/releases/tag/0.6.0) where it's written:

> Run Network Session with the application template "Network Session" or with the executable ray-network

**Comment by Houston4444** [comment]
You're right. I was talking about "add executable" action in RaySession itself.
So, I remove this mention from changelog.
