### ISSUE TITLE
Stuck in listing session loop

### ISSUE THREAD

**Issue by thoth-amon** [Houston4444/RaySession#213]
OS: Opensuse tumbleweed (GeekOS repo)
Version 0.14.2-2.1

Cannot open or start a new session.  The listing sessions animation is stuck on but nothing else happens. The new session option comes up but nothing happens when you press OK.

Starting from terminal shows the following error repeatedly

`AttributeError: module 'inspect' has no attribute 'getargspec'
Exception ignored in: 'liblo._msg_callback'
`

**Comment by Houston4444** [comment]
I answered directly here : https://github.com/geekosdawproject/geekosdaw-issues/issues/78#issuecomment-1799303123

**Comment by thoth-amon** [comment]
Thank you, this was fixed over there.
