### ISSUE TITLE
Add the software: ADLplug

### ISSUE THREAD

**Issue by jpcima** [Houston4444/RaySession#22]
Here: https://github.com/jpcima/ADLplug

It's a successor of adljack in Juce which has a Jack standalone with session support.
It is an extension having a full feature set, as opposed adljack which started as the basic implementation of a realtime synth. But I keep adljack around because some users prefer it, and also because it's the only option for Haiku compatibility.

The beta 4, latest release at the time of writing this, has basic NSM.
The master branch added `optional-gui` and `switch`.

**Comment by Houston4444** [comment]
Done.
