### ISSUE TITLE
JACK Patchbay is suddenly completely empty

### ISSUE THREAD

**Issue by rasmusq** [Houston4444/RaySession#227]
All of a sudden, the patchbay is completely blank on both my laptop and my desktop PC.
It happened right after an update on arch 2-4 days ago.
I am currently on version 0.14.3.
This holds true for both the -git version and the AUR version.
Current Kernel: `Linux rasmusq-desktop 6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux`

This is the terminal output:
```
% raysession      
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
qt.qpa.qgnomeplatform: Could not find color scheme  ""
[ray-daemon]GUI connected at osc.udp://rasmusq-desktop:19786/
[ray-daemon]URL : osc.udp://192.168.1.204:16187/
[ray-daemon]      osc.udp://rasmusq-desktop:16187/
[ray-daemon]ROOT: /home/rasmusq/Ray Sessions
[ray-daemon]Attempting to open /home/rasmusq/Ray Sessions/Default
marrouubma
[ray-daemon]Commanding smart clients to switch
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
[ray-daemon]Process has pid: 393084
[ray-daemon]The client "JACK Connections" at "osc.udp://192.168.1.204:19788/" informs us it's ready to receive commands.
[ray-daemon]Telling all clients that session is loaded...
[ray-daemon]Telling client JACK Connections that session is loaded.
[ray-daemon]Loaded
[ray-daemon]Done
[ray-daemon]patch sends clean
qt.qpa.qgnomeplatform: Could not find color scheme  ""
qt.qpa.qgnomeplatform: Could not find color scheme  ""
```

The patchbay in RaySession:
![image](https://github.com/Houston4444/RaySession/assets/53310290/9ef1d3a0-2bea-41f6-a2b4-32c56d7c485f)
The patchbay in Carla:
![image](https://github.com/Houston4444/RaySession/assets/53310290/cd4b78ef-26c0-4c10-af56-e554857e447d)

**Comment by bbeckoo** [comment]
I investigated this a bit and it's most probably alsa-python. There are some open issues.
https://github.com/alsa-project/alsa-python/issues/9

**Comment by xbelanch** [comment]
I dunno if that's the same issue but after last update I realized that Ray Session does not show nothing as before. I'm using pipewire btw.

**Comment by Houston4444** [comment]
Ok, I don't see anything in the logs that can help me to find what happens. I'll try to update my manjaro and see how it behaves (unfortunately manjaro update is verrrrrrrrry long, especially because I don't use it daily).

I suspect that the same happens for Patchance.

**Comment by Houston4444** [comment]
Nice news. Thanks for the investigation!

**Comment by waicool20** [comment]
Make a quick PKGBUILD for impatient arch users like me
```
_name=pyalsa
pkgname=python-pyalsa
pkgver=1.2.7
pkgrel=6
pkgdesc="Python binding for the ALSA library"
arch=(x86_64)
url="https://www.alsa-project.org"
license=(LGPL-2.1-or-later)
depends=(
  alsa-lib
  glibc
  python
)
makedepends=(
  python-build
  python-installer
  python-setuptools
  python-wheel
)
source=(git+https://github.com/FrancescoCeruti/alsa-python.git)
sha512sums=('SKIP')
validpgpkeys=(F04DF50737AC1A884C4B3D718380596DA6E59C91)  # ALSA Release Team (Package Signing Key v1) <release@alsa-project.org>

build() {
  cd alsa-python
  python -m build --wheel --no-isolation
}

package() {
  cd alsa-python
  python -m installer --destdir="$pkgdir" dist/*.whl
}
```

**Comment by SilenceFox** [comment]
> Make a quick PKGBUILD for impatient arch users like me
> 
> ```
> _name=pyalsa
> pkgname=python-pyalsa
> pkgver=1.2.7
> pkgrel=6
> pkgdesc="Python binding for the ALSA library"
> arch=(x86_64)
> url="https://www.alsa-project.org"
> license=(LGPL-2.1-or-later)
> depends=(
>   alsa-lib
>   glibc
>   python
> )
> makedepends=(
>   python-build
>   python-installer
>   python-setuptools
>   python-wheel
> )
> source=(git+https://github.com/FrancescoCeruti/alsa-python.git)
> sha512sums=('SKIP')
> validpgpkeys=(F04DF50737AC1A884C4B3D718380596DA6E59C91)  # ALSA Release Team (Package Signing Key v1) <release@alsa-project.org>
> 
> build() {
>   cd alsa-python
>   python -m build --wheel --no-isolation
> }
> 
> package() {
>   cd alsa-python
>   python -m installer --destdir="$pkgdir" dist/*.whl
> }
> ```

First of all, thank you !
Here's some instructions in case anyone stumbles here

First clone the fork:
`git clone https://github.com/FrancescoCeruti/alsa-python`
then cd into it:
`cd alsa-python`
then make a new file called PKGBUILD:
`touch PKGBUILD`
Paste the above inside the PKGBUILD file and run the following
`makepkg -si`

**Comment by bbeckoo** [comment]
FIXED: https://github.com/alsa-project/alsa-python/releases/tag/v1.2.12

**Comment by rasmusq** [comment]
I am not having the problem anymore after this update, closing
