### ISSUE TITLE
Sink and Source with Pipewire

### ISSUE THREAD

**Issue by CarlBcx** [Houston4444/RaySession#229]
I recently migrated from Xubuntu 23.10 to 24.04. Everything went well.
It seems like now I'm with Pipewire.
I use Raysession with an external sound card.

Before the migration I had a "Sink" and a "Source" which allowed me to connect non-compatible applications. I do not have them anymore.

Running qjackctl alone, I once saw a "pipewire" block with inputs and outputs.
I wonder if this replaces Sink and Source.
But I don't see him anymore.

In Raysession I don't have this block either.
Do you know how I can have Sink and Source or the Pipewire equivalent?
I really need it...

Thank you in advance for the answers.

**Comment by CarlBcx** [comment]
Finaly because with pipewire I can all interconnect I don't need Sink and Source anymore.
So problem solved !

**Comment by luzpaz** [comment]
Ticket still relevant ?
