### ISSUE TITLE
Raysession and Pipewire

### ISSUE THREAD

**Issue by CarlBcx** [Houston4444/RaySession#230]
I realized that with Pipewire I don't need Jack.
I tried qpwgraph and natively I have access to all sound cards and audio and video devices.
Only Raysession is much better designed and much more practical.

In the Raysession documentation it is indicated for Jack (or Pipewire).
But I couldn't find anywhere in the documentation how to connect it directly to Pipewire without Jack.
Can anyone help me?

**Comment by Houston4444** [comment]
Hi, RaySession works with PipeWire because PipeWire can pretend to be JACK. 
Depending on your distro, you may have to install pipewire-jack package.

**Comment by CarlBcx** [comment]
Thanks for the answer.
I discovered it's works perfectly with "pw-jack raysession".
