### ISSUE TITLE
New Qtractor Session can't work on RaySession. (Ubuntu Studio 24.04 LTS)

### ISSUE THREAD

**Issue by OKKyu** [Houston4444/RaySession#233]
Hello. May I ask a question?  I could add qtractor as application on RaySession, but when I try to show gui, there are no response and can't display qtractor's gui. It seems to  qtractor is freeze. I report details below.
  Environment:
    Ubuntu Studio 24.04 LTS (both usb live and upgrade from 22.04)
    RaySession  version 0.14.3-0ubuntu2
    Qtractor       0.9.39-1build3
  Trying Operation and Result:
    1)launch RaysSession -> Add Qtractor by NSM Template (not Ray-Hack, non custom executable) -> try to show gui -> no response...  Strangely enough, Created Qtractor have two Maser midi port by defalut.
![01 TryingOperation-ng](https://github.com/user-attachments/assets/26639de1-340e-4881-8326-6d949d820853)

    2)launch Qtractor without RaySession -> it works normally. 
       Created Qtractor have only one Maser midi port by defalut.
![02 TryingOperation-work](https://github.com/user-attachments/assets/3f62f596-7109-40e7-a9d5-e1851c588c73)

Is it bug that when RaySession creating Qtractor's midi port?  and How can i do it?

**Comment by Houston4444** [comment]
I think you should report this bug to Qtractor's dev (maybe it has already been done). However, I think that the fact there are 2 midi ports is not linked to the bug. Here, I have an older Qtractor version, working well with RaySession, it also has 2 master alsa midi ports

**Comment by OKKyu** [comment]
Thank you reply. but May I ask some question?
1)  Please teach me to older Qtractor's version. I tried older vertion 0.9.25 ( this version is working wit RaySession on UbuntuStudio22), but It coudn't work on UbuntuStudio24.  I got this version with command "apt-get download qtractor", and I installed it on UbuntuStudio24, but qtractor coudn't work.

2) because of Recent Screenshot had only RaySession's Screen,  I captured Jack Audio Connection Kit's Graph. certainly there are two master alsa midi port, But there are also two master Midi-Bridge port. What's Happen this ?
![UbuntuStudio24-Qtractor-with-RaySession](https://github.com/user-attachments/assets/c42b1c7c-2557-4baf-9273-3128e7561768)

additionally,  without RaySession, there are only one master Midi-Birdge port and one master alsa midi port.
![UbuntuStudio24-Qtractor-without-RaySession](https://github.com/user-attachments/assets/8cb8e44c-f847-4592-9d5a-50976757d045)

if this bug cause by qtractor, why master port appear only one port when qtractor runned without RaySession? looks from beginner's eye,  This bug  looks RaySession's Bug when RaySession try to call qtractor with application template.

**Comment by Houston4444** [comment]
> Please teach me to older Qtractor's version. 

```
$ qtractor --version
Qtractor 0.9.90
Qt: 6.4.2
```

> because of Recent Screenshot had only RaySession's Screen, I captured Jack Audio Connection Kit's Graph. certainly there are two master alsa midi port, But there are also two master Midi-Bridge port. What's Happen this ?

Yes, I have them too (note that you can display alsa midi ports with RaySession directly, right click -> Canvas options -> provide ALSA MIDI ports). I don't know why there are 2 master midi ports.

> if this bug cause by qtractor, why master port appear only one port when qtractor runned without RaySession? looks from beginner's eye, This bug looks RaySession's Bug when RaySession try to call qtractor with application template.

RaySession only starts Qtractor with the NSM protocol, RaySession does not call Qtractor with application template. Qtractor itself choose what it has to do when started under NSM. The proof that RaySession is not at the origin of the bug is that the same happens with new-session-manager (http://linuxmao.org/tiki-view_forum_thread.php?forumId=27&threadId=116482&comzone=show#threadId116482).

**Comment by Houston4444** [comment]
Oups, sorry, I checked Qtractor too fastly, it is not working at all indeed with my version (window never appears or is frozen).

**Comment by Houston4444** [comment]
It seems to be fixed now, see https://github.com/rncbc/qtractor/issues/464 .

So I think I can close this issue.
Regards.

**Comment by OKKyu** [comment]
Thank you reply for me. I'm sorry about doubting raysesson. I watched rncbc/qtractor#464 and I'm trying to other qtractor version. I encountered another problem, I will contact to rncbc next time.
Let's close this issue. Thank you!

**Comment by Houston4444** [comment]
>  I'm sorry about doubting raysesson

Don't apologize for that, no software is perfect ! Greetings.
