### ISSUE TITLE
git doesn't stop normally (with pipewire pw-jack raysession)

### ISSUE THREAD

**Issue by magicvince** [Houston4444/RaySession#237]
Good news (for me) with Linux Mint Debian Edtion (LMDE6 based on Debian 12), starting raysession with pipewire is a simple to launch all my music and sound application directly from RaySession.

but I'm in trouble when I try to save a session (or quit and save). I've got an error message "git ne s'est pas arrêté normalement init".

When I restart my session, the application, hack and executable are here but the last connections are lost.

here's the return of the terminal during the session if I started with the command pw-jack raysession

```
me@myordi:~$ pw-jack raysession
[ray-daemon]GUI connected at osc.udp://hpbuanderie:12860/
[ray-daemon]URL : osc.udp://192.168.0.5:16187/
[ray-daemon]      osc.udp://myordi:16187/
[ray-daemon]ROOT: /home/me/Ray Sessions
[ray-daemon]Attempting to open /home/me/Ray Sessions/Clavier-Guitare-Voix
me[ray-daemon]Commanding smart clients to switch
[ray-daemon]Process has pid: 72688
[ray-daemon]The client "JACK Connections" at "osc.udp://127.0.0.1:12865/" informs us it's ready to receive commands.
[ray-daemon]patch sends dirty

[Qtractor-qtractor]

(qtractor:72703): GLib-GObject-WARNING **: 01:24:43.357: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'

(qtractor:72703): GLib-GObject-WARNING **: 01:24:43.389: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'

(qtractor:72703): GLib-GObject-WARNING **: 01:24:43.419: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'

(qtractor:72703): GLib-GObject-WARNING **: 01:24:43.424: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-application-prefer-dark-theme'

[ray-daemon]Process has pid: 72703
[ray-daemon]The client "Qtractor" at "osc.udp://127.0.0.1:12866/" informs us it's ready to receive commands.
[ray-daemon]qtractor sends clean
[ray-daemon]Telling all clients that session is loaded...
[ray-daemon]Client 'qtractor' sends gui hidden
[ray-daemon]Telling client JACK Connections that session is loaded.
[ray-daemon]Telling client Qtractor that session is loaded.
[ray-daemon]Loaded
[ray-daemon]Done
[ray-daemon]Telling JACK Connections to save
[ray-daemon]Telling Qtractor to save
[ray-daemon]qtractor sends clean
[ray-daemon]patch sends clean
[ray-daemon]Session Clavier-Guitare-Voix saved.
[ray-daemon]git ne s'est pas arrêté normalement.
init
[ray-daemon]can't snapshot
[ray-daemon]Done
[ray-daemon]Bye Bye...
```
Thanks for help

**Comment by Houston4444** [comment]
Hi !

> but I'm in trouble when I try to save a session (or quit and save). I've got an error message "git ne s'est pas arrêté normalement init".

> When I restart my session, the application, hack and executable are here but the last connections are lost.

The 2 problems are not linked. Save is done before snapshot, and even if git fails to make a snapshot, connections are already saved.

I don't know why git fails to snapshot (it is really not verbose in your case), but I suggest to remove the '.ray-snapshots' hidden folder in your session directory and try again.

For the connections, are you sure that programs have always the same JACK client names in the patchbay ? I mean, If you right click on a port and choose 'Informations', is the full name of the port strictly the same than at previous session load. Automatic connections depends on port names, if the names are not strictly the same, it is normal that connections seems to be not restored.

**Comment by magicvince** [comment]
Thanks for answer.
For connections I maybe two differents problems, but one seems to be solved.
- Some of my qtractor output patch wasn't saved when I use Raysession diagrams. But if I set up the output in Qtractor, the patch is saved correctly (could be considered as solved for use)
- I don't know why but my midi pedal guitar seems to be recognize after reboot, I have to unplug and plug the usb connector. During session. It's seems to be ok. I record the jack id in the patchbay to compare after next reboot.

For the git fails … I didn't find any .ray-snapshots (in my ~/ or ~/.confg/raysession or in folders of my Ray Sessions directory).

**Comment by Houston4444** [comment]
> Some of my qtractor output patch wasn't saved when I use Raysession diagrams.

On my side, it is a problem. Are the connections saved in the jackpatch file ? (file which name ends with `.patch.xml` in the session folder).

> I don't know why but my midi pedal guitar seems to be recognize after reboot, I have to unplug and plug the usb connector. During session. It's seems to be ok. I record the jack id in the patchbay to compare after next reboot.

I think that the problem is that Midi-Bridge writes the ALSA client identifier in the midi port name, and this client id can be different at each unplug/plug. A2J (tool used with JACK to create one JackMidi port for each MIDI ALSA port) has an option for this (--dup  : Disallow unique port names), probably pipewire has something identical.

> For the git fails … I didn't find any .ray-snapshots (in my ~/ or ~/.confg/raysession or in folders of my Ray Sessions directory).

mmmh, probably git is not able to init the session project at all, could you go to your session folder with a terminal and execute the following command:

```
git --work-tree "$PWD" --git-dir "$PWD/.ray-snapshots" init
```

**Comment by magicvince** [comment]
First, I'm maybe an idiot… git doesn't work, because I'm on a fresh install and I didn't understand when I installed RaySession, that git is mandatory. Trying to run your git command remember me a basic sudo apt install git can help me !!!
-> git fail solved

Midi Device (FBV pedal board) continue, don't find in the pipewire documentation something  --dup option. I still work in this direction. The device doesnt lost his id during a user session (I can plugged/unplugged and the patch stay correct). But the id will be lost at each reboot. Don't know if I chek in the patchbay prefs "fournir les port Alsa midi" have an impact (I'll test with my next reboot)

Saving session connexion seems to be ok (don't why, It works.…).

**Comment by Houston4444** [comment]
> First, I'm maybe an idiot… git doesn't work, because I'm on a fresh install and I didn't understand when I installed RaySession, that git is mandatory. Trying to run your git command remember me a basic sudo apt install git can help me !!!

Don't blame yourself, there is a little bug indeed, RS should not try to use git if it is not installed (it can works without, but without snapshots of course).

> Don't know if I chek in the patchbay prefs "fournir les port Alsa midi" have an impact (I'll test with my next reboot)

It should not, it is not the same part of the program at all. Note that, as you have a "JACK connections" client which saves the JACK connections (by default in new session), you can have an "ALSA connections" client which saves the ALSA connections. It could be used as a workaround if you don't find the option to disable unique id. For example, you can plug ALSA port of your pedal guitar to "Midi Through", then the Jack Midi "midi through" will always sends events receive from your pedal guitar.

> Saving session connexion seems to be ok (don't why, It works.…).

ah ! Good new.

**Comment by magicvince** [comment]
Thanks for your answers. I will try to manage my pedal with miditrough. I'll be back here or in a dedicated thread to report how it works.

I really appreciate raysession to manage easily the transition to pipewire. :+1:
