### ISSUE TITLE
ModuleNotFoundError: No module named 'patshared'

### ISSUE THREAD

**Issue by crshrprt** [Houston4444/RaySession#238]
Trying to run latest RaySession [e97043b](https://github.com/Houston4444/RaySession/commit/e97043ba7f67093956a2b44ad8c280f094a07d13) on Debian Sid I encounter the following error:
 ```
$ raysession 
Traceback (most recent call last):
  File "/usr/local/share/raysession/src/bin/ray-daemon", line 15, in <module>
    from osc_server_thread import OscServerThread
  File "/usr/local/share/raysession/src/daemon/osc_server_thread.py", line 31, in <module>
    from patshared import GroupPos
ModuleNotFoundError: No module named 'patshared'
```

**Comment by Houston4444** [comment]
Hi. I can't reproduce. I think you need to update submodules.

**Comment by crshrprt** [comment]
Weird, I have the same error on 3 different machines (all Debian Sid, where RaySession was working before latest commits).
It happens also if I `sudo make uninstall`, delete the RaySession repo and I clone it fresh:
```
git clone --recurse-submodules https://github.com/Houston4444/RaySession.git
cd ~/opt/RaySession/
make -j4
sudo make install
```
I'm doing something wrong?

**Comment by crshrprt** [comment]
It works now! Thank you very much.
