### ISSUE TITLE
traceback error when loading an existing session with jack patchbay included.

### ISSUE THREAD

**Issue by toadzrock** [Houston4444/RaySession#239]
I recently updated my system, and installed raysession from the latest git at the time of posting this issue. When I open the session, which contains jackpatch, linuxsampler, and a bash executable containing my template .lscp file for linuxsampler, the linuxsampler apps load ok, but the raysession gui disappears, and i have to trawl through btop to close everything manually.

```
Traceback (most recent call last):
  File "/home/jack/Downloads/git/RaySession/src/gui/gui_session.py", line 155, in _osc_receive
    function(path, args)
  File "/home/jack/Downloads/git/RaySession/src/gui/gui_session.py", line 541, in _ray_gui_patchbay_fast_temp_file_running
    self.patchbay_manager.fast_temp_file_running(*args)
  File "/home/jack/Downloads/git/RaySession/src/gui/ray_patchbay_manager.py", line 532, in fast_temp_file_running
    self.add_port(p.get('name'), p.get('type'),
  File "/home/jack/Downloads/git/RaySession/src/gui/patchbay/patchbay_manager.py", line 77, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/Downloads/git/RaySession/src/gui/patchbay/patchbay_manager.py", line 1187, in add_port
    group.check_for_portgroup_on_last_port()
  File "/home/jack/Downloads/git/RaySession/src/gui/patchbay/base_group.py", line 760, in check_for_portgroup_on_last_port
    other_port = self.stereo_detection(last_port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/Downloads/git/RaySession/src/gui/patchbay/base_group.py", line 660, in stereo_detection
    while base_port[-1].isdigit():
          ~~~~~~~~~^^^^
IndexError: string index out of range
Aborted
```

Any clues?

EDIT: I've just installed patchance to find out if the error occurs there too (chasing the possibility of a python error)
and the same traceback error occurs there too. 
I start linuxsampler from the command line, then feed it the .lscp file to load my orchestral template. It's at that moment the traceback error occurs.

Note that linuxsampler and the lscp file load with no problems when started from a terminal.

I'm continuing to investigate....

EDIT2: 
I've regressed to build 0.14.3, and that works. So the challenge is sometime after that as the 0.14.4 build didn't work either.
Hope this helps.

**Comment by Houston4444** [comment]
> , but the raysession gui disappears, and i have to trawl through btop to close everything manually.

Only the gui crashes, did you try to simply restart RaySession? it should reconnect to the daemon, but it could also crash directly. 

Could you send the result of `jack_lsp` when linuxsampler is loaded?

**Comment by toadzrock** [comment]
I did try restarting but the gui wouldn't load.

Here's all the ports currently showing in a 0.14.3. install of Raysession.

[jack_lsp-1.txt](https://github.com/user-attachments/files/17813756/jack_lsp-1.txt)

**Comment by Houston4444** [comment]
The problems seems to come from the fact some ports contain only digits in their names. I just pushed a little fix, please update and try again.

Thanks.

**Comment by toadzrock** [comment]
It's working again.

Thanks for the fix.
