### ISSUE TITLE
Feature request: open session from command-line

### ISSUE THREAD

**Issue by mxmilkb** [Houston4444/RaySession#26]
Inspired by [this LM thread](https://linuxmusicians.com/viewtopic.php?f=4&t=19279).

**Comment by Houston4444** [comment]
Done on git master.
Option is `-s session_name`, it's callable from raysession or ray-daemon.
session_name can be an absolute path too.
Note that an empty session will be created if session_name doesn't exists.

**Comment by Lasakro** [comment]
Thanks Houston and Milk. I'll give it a try.

**Comment by mxmilkb** [comment]
See also https://github.com/rikberkelder/non/commit/ec5b3d604a64c3fea3649736804a1f2361360d32

**Comment by trebmuh** [comment]
@Houston4444 can you make it a part of the `raysession --help` output ?

**Comment by trebmuh** [comment]
Well, I gave it a shoot in the dark. Please double, even triple-check this works before merging. I take no responsibility, ever.

**Comment by Houston4444** [comment]
Done yet.
