### ISSUE TITLE
Application request: patroneo, etc.

### ISSUE THREAD

**Issue by mxmilkb** [Houston4444/RaySession#28]
I'd like to request [patroneo](https://www.laborejo.org/software.html) be added to the Factory Application menu list.

Also, how about adding the others on http://non.tuxfamily.org/wiki/ApplicationsSupportingNsm?

**Comment by Houston4444** [comment]
Since yesterday. I am looking to Patroneo and Laborajo suite.
There is a bug I have to fix that make them crash at restart (because of raysession's GUI state recall).
So It will be done soon.

I note Synthpod and MFP missing in this list.

**Comment by Houston4444** [comment]
Done.
