### ISSUE TITLE
Support double click for opening a session

### ISSUE THREAD

**Issue by ycollet** [Houston4444/RaySession#33]
Support the double click on the session name to open it.
Currently, I must select the session name and then click on "open".

**Comment by Houston4444** [comment]
Why not. I'll try to do that when I will rework the open session dialog.

**Comment by Houston4444** [comment]
Done among many little things.
Please test and close this issue if you think it works well.

**Comment by ycollet** [comment]
I just packaged RaySession 0.8.0 for Fedora on:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/

The double click works nicely and it will be very useful !

I close the request.

Thanks a lot.
