### ISSUE TITLE
Bad symbolic link src/bin/ray_control in 0.8.2

### ISSUE THREAD

**Issue by eeickmeyer** [Houston4444/RaySession#35]
I see that this has already been fixed, but is there any chance we could get a quick 0.8.3 release? I am unable to build this without lintian errors due to this issue, nor is there a way to directly patch this.

**Comment by Houston4444** [comment]
Oups, sorry for this, that's done.
Please try v0.8.3 and close this issue if it works well now.

**Comment by eeickmeyer** [comment]
Yes, that worked. Thank you!
