### ISSUE TITLE
raysession.desktop includes invalid category

### ISSUE THREAD

**Issue by eeickmeyer** [Houston4444/RaySession#38]
"AudioEditing" is not a valid XDG category. I use this patch for packages on Fedora and Ubuntu:

```
Index: raysession/data/raysession.desktop
===================================================================
--- raysession.orig/data/raysession.desktop
+++ raysession/data/raysession.desktop
@@ -7,4 +7,4 @@ Exec=raysession
 Icon=raysession
 Terminal=false
 Type=Application
-Categories=AudioVideo;AudioEditing;Qt;
+Categories=AudioVideo;Audio;Qt;

```

**Comment by Houston4444** [comment]
Strange, this category is used by Ardour itself, but I can remove it, no problem.

**Comment by trebmuh** [comment]
See [https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html].

**Comment by trebmuh** [comment]
"AudioEditing" is a specificity for AVlinux. See https://tracker.ardour.org/view.php?id=4566 .

**Comment by Houston4444** [comment]
Done, same as your patch. Thanks
