### ISSUE TITLE
src/shared/jacklib.py includes unnecessary shebang

### ISSUE THREAD

**Issue by eeickmeyer** [Houston4444/RaySession#39]
The shebang included in jacklib.py implies it is executable when it is, in fact, not meant for execution. However, the directory it installs to is for executable files. Therefore, the shebang is incorrect.  I use the following patch for my Fedora package:

```
From: Erich Eickmeyer <erich@ericheickmeyer.com>
Date: Sat, 8 Feb 2020 20:32:29 -0800
Subject: [PATCH] remove unnecessary shebang

---
 src/shared/jacklib.py | 1 -
 1 file changed, 1 deletion(-)

diff --git a/src/shared/jacklib.py b/src/shared/jacklib.py
index fe0ae10..9a4a082 100644
--- a/src/shared/jacklib.py
+++ b/src/shared/jacklib.py
@@ -1,4 +1,3 @@
-#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 
 # JACK ctypes definitions for usage in python applications
-- 
2.24.1

```

**Comment by Houston4444** [comment]
You're right, I'll change it !

**Comment by Houston4444** [comment]
Done. Note that this file has been copied from Cadence https://github.com/falkTX/Cadence/blob/master/src/jacklib.py .
