### ISSUE TITLE
"Session is locked by another process"

### ISSUE THREAD

**Issue by zigmhount** [Houston4444/RaySession#46]
Hi again,

So I just tested the snapshot feature and I'm having an issue: when I try to load a snapshot, I always get the message "Session is locked by another process". I don't get that when closing Ray and opening the session, which will then be the snapshot I wanted to open before.

When running `raysession -d` I see the following:
```
[ray-daemon-git reset --hard]
HEAD is now at ba44d6c ray

[ray-daemon-git checkout 2020_4_24_20_52_5]
Previous HEAD position was ba44d6c ray
HEAD is now at 24d3a33 ray

[ray-daemon]Failed
OSC::daemon sends ('/error', '/ray/session/open_snapshot', -11, 'Session is locked by another process!')
OSC::daemon sends ('/ray/gui/server/status', 8)
OSC::gui_receives /error, sis, ['/ray/session/open_snapshot', -11, 'Session is locked by another process!'], osc.udp://192.168.1.129:16187/
OSC::gui_receives /ray/gui/server/status, i, [8], osc.udp://192.168.1.129:16187/
```

And if I *don't* run with the `-d ` option, I see this once I press cancel on the "Session is locked" message window:
```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 16942, resource id: 8395992, major code: 40 (TranslateCoords), minor code: 0
```

I get this every time I open a snapshot of this session.

**Comment by Houston4444** [comment]
ah, this is a bug.
Which version is in use ? github master, latest release ?

**Comment by Houston4444** [comment]
Ok, It was a very strong bug in github master, thanks you very much for the report.
Now it should be fixed, please try again.

Has this bug seriously corrupted an important session ? If it is the case, I am sorry for that, but I could help you to recover your data.

**Comment by zigmhount** [comment]
Great to hear! Sorry I didn't respond earlier, I haven't opened the laptop yet today, but I'll let you know as soon as I try out the fix (probably in 2-3h from now)

Actually I don't think it corrupted anything, the session just opened properly after closing and reopening RaySession - and in any case it was only a test project to try out the snapshots so there was absolutely nothing to lose :)

**Comment by zigmhount** [comment]
Works very nicely now, thanks!

However I got the following problem when building:
```lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory```
which I didn't get when building RaySession yesterday. I get the same error when I run `lrelease`alone in a different folder so I guess it's a problem with my install, but reinstalling the package `pyqt5-dev-tools` didn't help, so in the end I used `make LRELEASE=true` so it finished to build, but not translated. Not sure whether it's a problem in RaySession or only on my computer.

**Comment by Houston4444** [comment]
Good.

Je ne comprends pas pourquoi lrelease aurait changé en cours de route, peut-être une mise à jour de ton système ou que sais-je.
Mais, en gros, pour avoir la traduction, LRELEASE doit être soit lrelease, lrelease-qt4 ou lrelease-qt5 selon l'executable présent sur ton système.

**Comment by zigmhount** [comment]
Bah oui je sais pas non plus, j'ai bien lrelease (pas -qt4 ou -qt5) mais il me donne l'erreur ci-dessus.
Du coup le vrai bug est réglé, et je me pencherai sur lrelease un autre jour,. Merci !
