### ISSUE TITLE
Issue with DrumkV1

### ISSUE THREAD

**Issue by sub26nico** [Houston4444/RaySession#5]
I made a session with seq24 and DrumkV1. I loaded 2 samples (kick and snare) in DrimkV1 
and save the preset. Then save the session. When I reloaded the session, DrumkV1 doesn't 
load the samples, the preset is loaded but without the samples.

**Comment by Houston4444** [comment]
Can't reproduce !
Which version of Drumkv1 do you use ?
On my system it works correctly with Drumkv1 0.8.6.

**Comment by sub26nico** [comment]
Same here, version: 0.8.6.

**Comment by sub26nico** [comment]
I found it. Drumk1 re-open his preset from the path of the NSM session. If you change the preset, 
you have to save it in this path or give the new preset the same name and erase the old.

**Comment by Houston4444** [comment]
As I said, Vee One Suite NSM implementation is not very well done.
NSM clients MUST disable "open/new".

**Comment by sub26nico** [comment]
Ok, do you want I close here ?

**Comment by Houston4444** [comment]
first we need to send issue to Vee One Suite devs !

**Comment by sub26nico** [comment]
Done

**Comment by sub26nico** [comment]
rncbc have made a new version. It seems to be better but DrumkV1 can't reload a preset if it is not 
in the session folder.

**Comment by rncbc** [comment]
> As I said, Vee One Suite NSM implementation is not very well done.
> NSM clients MUST disable "open/new".

ahem, pardon me to interrupt :) v1's author here B)

although I do find myself that the "open/new" restriction on NSM is complete BS, and I have discussed that with male before (non-stuff's author), I should tell that all of the V1's New, Open and Save (preset) operations are quite meaningless to a particular NSM session state: they all serve as "tools" of convenience for the user; none of those, so called native operations, interfere with a NSM session, whatsoever; they just change  internal state of a session participant as a localized parameter or change should go (drumkv1_jack in this particular case); they not imply any direct nor immediate NSM operation whatsoever.

thanks for listening.
byee

**Comment by Houston4444** [comment]
All apologies. You're right ! If Open/New relies to preset and not session file, no reason to prevent to use them.

I am curious to know what makes crash raysession on your system. For the moment it hasn't been tested on various distributions. Obviously, at home it doesn't crash in normal use.

It's still work in progress !

Thanks

**Comment by Houston4444** [comment]
rncbc, I think to that now, you may have clone the master of RaySession yesterday in the middle of afternoon (Europe hour). I did a mistake in code that broke it. I repaired it few hours after. If it is this, you should retry and see. Thanks

**Comment by sub26nico** [comment]
With the new release of Ray Session (and the drumkv1's one), no more problem. 
Ray Session still rename the DrumkV1's preset 'nameofthesession.drumkv1' in the session folder, 
but DrumkV1 remembers the last presets used (with the real names) and can reload them quickly. 
No more problem for me to use the 2 applications together.
As I said to rncbc, thanks for the time given on this situation.
