### ISSUE TITLE
DeprecationWarning on master branch ray_control execution

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#51]
Hello,

I have this warning running ray_control on the master branch.

` /usr/local/share/raysession/src/bin/ray_control:474: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()

BR,
Laurent

**Comment by Houston4444** [comment]
Hi,
it concerns the liblo lib, not my code.
But I've got to hide deprecation warnings in ray_control, sure.

**Comment by Houston4444** [comment]
The deprecation warning should not appears anymore (for a long time now).
