### ISSUE TITLE
When program exit with error status (exit_code = 1), the ray-proxy doesn't notice the program stopped.

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#58]
Hello,

I have a script wrapper that starts programs with the exec command for each ray-proxy

It checks for program availability on the system and when the program is not found it prints an error message and exit with status 1 but ray-proxy does not mark the process as stopped.

Is there a command or another exit code to be used for telling raysession that the program could not be started successfully ?

BR,
Laurent

**Comment by Houston4444** [comment]
That is quite strange. I don't see why. Does your script run python ? If yes, it's possible that you need to run python with '-u' option, at end of file header   #!/usr/bin/python3 -u

**Comment by newlaurent62** [comment]
No it's a bash script (see attached file).
[alt-config-session.tar.gz](https://github.com/Houston4444/RaySession/files/4669917/alt-config-session.tar.gz)

**Comment by Houston4444** [comment]
ray-proxy prefers to not stop and display its window if the command ends too fastly. If it didn't that, user would not have any GUI way to set proxy parameters. So, this is not really a bug.
