### ISSUE TITLE
Open proxy dir shortcut

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#76]
Hello,

Proxy dirs can hold several dirs such as .config data bin... It may be useful to add a shortcut to open proxy dir (with hided files showed) in ray-proxy GUI.

BR,
Laurent

**Comment by Houston4444** [comment]
Hi.
Ray-Hack protocol is now available, so it could be in Client properties, in Ray-Hack tab.
However, I don't think it is possible to show hidden files with xdg-open (which is the good command to launch file manager by default on the system).
