### ISSUE TITLE
What if Jack server is stopped while a session is running ?

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#78]
Hello,

When Jack server is stopped while a session is opened and clients are started, this may lead to unstable state ... 

There are several case in the real world:

- In the best world, the application use jack but is not affected by this and all is fine
- The application displays an error message : we don't get the information until we see/read the message ... (This is a problem when several window are fired ...)
- The application crashes unexpectedly ...
- the application does not use jack, all is fine

May be an icon or a message in RaySession software should remind to the user that the jack server has been restarted or stopped and that the jack clients may be in unstable state ?

How RaySession address this ?

BR,
Laurent

**Comment by Houston4444** [comment]
Each program has its role and RaySession has nothing to do with JACK (except ray-jackpatch client).
If user needs a GUI to display JACK state, (s)he uses Cadence or QJackCtl.
Don't forget that users can benefit of session management even without JACK, with audio softwares on ALSA, PulseAudio or on coming Pipewire , even with non audio softwares.

That said, I think in real world JACK is used 99 % of the time, but it can change in the future with Pipewire. More, almost users will simply have JACK running all over the time with the same parameters and they really don't need that RS displays theses informations. This is my case and what I suggest for a good user experience. Personally, what I miss is something displaying JACK infos at desktop level, on the panel (plasma widget for KDE).

**Comment by newlaurent62** [comment]
I understand that RS has nothing to do with Jack in the general case but you already developped plug-ins to support jack. 

What i ask for is to dispose some ray_control API to handle situation where Jack is in unwanted state (killed or crashed). You have already done a lot with Jack parameters handling and the jack checker daemon and this is not hardcoded in RS but kindly use by the sessions that need it.

The handling of such situation (Jack server killed or crashed) could be developped as an event session handler (define when an event has to be raised and define how to react to this event).

This should allow to include Jack related stuff in RS plug-ins code and let each session handle Jack events when needed. A generic case could be define though if needed.

**Comment by newlaurent62** [comment]
I don't know if this is the right way but some command line like:

ray_control handler eventname executable
ray_control fire eventname

So we can have an executable (jack client) that register to jack server and tells when it is killed or crashed.

And a script or other executable that handles the event.

**Comment by Houston4444** [comment]
I confess I don't understand.
Anyway when JACK crashes, if it affects some clients, they will be the first to inform the user.
It's always an unpleasant situation, but I don't see how RS could be of any help.
What kind of RS behavior would you except ?

**Comment by newlaurent62** [comment]
In one of my use case, i have applications that display a message when jack is killed and they stop running. So i have a bunch of applications that stop running. My session is unusable in this state. I have only one message that pops up and all others are hidden ...

The behavior i would expect in my session is to restart jack and all applications that runs off when jack server is killed or crashed unless an option has been activated (RESTART_AUTO=false in ray-scripts/.env) ... with a message in RaySession logs saying it has restarting the session because of jack failure.

This would allow in my case, to minimize the interrupt of service ... even if it's not ideal. (I would rather prefer no interruption at all) 

Donc ce qui pourrait être utile dans ce cas:

- un exécutable qui génére un événement grâce à ray_control quand le serveur jack plante ou est killé. Ce programme pourrait être réutilisé par d'autres sessions. Typiquement ce serait un client jack qui s'enregistre auprès du serveur jack et qui générerait un événement grâce à la commande suivante:

**prototype:**
`ray_control fireevent $eventname $params...`

**exemple:**
`ray_control fireevent jack_killed ${jack_server_name}`
 
- un exécutable qui définit le comportement à avoir quand l'évenement est généré
Un script de ce style:
https://github.com/Houston4444/RaySession/issues/74#issuecomment-643633656

que ray_control exécute car le gestionnaire d'événements s'est enregistré au chargement de la session grâce à la commande suivante:
ray_control eventhandler jack_killed_handler.sh

Au final ray_control exécutera : 
`$eventhandler $eventtype $eventparams`
exemple:
`jack_killed_handler.sh jack_killed ${jack_server_name}`

**Comment by Houston4444** [comment]
Salut,
Non, je ne vais pas faire ça, ça me paraît surfait.
D'ailleurs, je ne vois pas bien pourquoi tu aurais besoin que RaySession gère cela, tu pourrais tout simplement avoir un démon que tu lances via un script de session par exemple.

En python, tu peux utiliser la lib src/shared/jacklib.py pour créer un client JACK.

Tu peux tout aussi bien (et c'est sans doute plus simple) faire tourner un démon dbus qui se connecte à des événements JACK, le ray-jack_checker_daemon te donnera un exemple, tu peux utiliser la commande `qdbus` pour connaître les méthodes disponibles.
Par exemple
`qdus org.jackaudio.service /org/jackaudio/Controller`
te donnera la listes des méthodes et signaux disponibles pour JACK.
Avec un peu de documentation, tu devrais parvenir à connecter `org.jackaudio.JackControl.ServerStopped` à ton script de redémarrage de JACK.

**Comment by newlaurent62** [comment]
ok je vais regarder ça merci.
