### ISSUE TITLE
Client template not proprely saved if the current session is not saved.

### ISSUE THREAD

**Issue by moonshaadow** [Houston4444/RaySession#82]
I've tried to create some Carla templates (with some plugins in it). If the session or the client hasn't been saved before, the template will be only an empty Carla.
Not a big deal when we know it, but if the user creates templates and abort session, his work will be lost.

**Comment by Houston4444** [comment]
> If the session or the client hasn't been saved before, the template will be only an empty Carla.

It's more right to say, when the client has not been saved before.
Yes, save as template doesn't save the client first.
That's probably right, user will in most cases want to save the client before saving it as template (if the client is started).

That could be a GUI thing, with a checked check box "Save the client before save it as template".

**Comment by moonshaadow** [comment]
> That's probably right, user will in most cases want to save the client before saving it as template

I'm not sure, we could want to save a template, but not the client in the current session.
Different cases : 
- "What I have done is a good idea, I want to save it as template" -> yes, I probably would  save the client before
- "I will create some templates to improve my further work and make it faster" -> In this case user may not want to save the client. That's what I have done, I have created several templates with different states of a same Carla client, not saving the client. Result is empty carla templates.

In my mind the template's saving should be independent from client's saving.

**Comment by Houston4444** [comment]
If what you want is something saving as template the current state (with unsaved changes) of a program (here carla), but not save the client, I am sorry, it is impossible.
Template mechanism copy files of the client (with renaming) to the config folder.
Programs writes theses files when we save them, so we can't save as template non yet existing files.
Or it would means, backup the client files, save the client, save as template, and reput the backup in place, but this is a terrible insanity, we can't know how will react some programs but we can have some ideas, imagine moving Ardour audio folder while playing transport :( .

> In my mind the template's saving should be independent from client's saving.

In that case, there is no problem, this is exactly the way it works for now ;)

**Comment by moonshaadow** [comment]
Ok, it makes sense to me now. Such a feature would call a 'save as' function from the client, if it exists, and we can easily imagine it won't work with some programs.
So I understand your first proposition, it could be a reminder to the user in case he/she needs to save client before.
