### ISSUE TITLE
Setting server osc port when running raysession

### ISSUE THREAD

**Issue by markjfisher** [Houston4444/RaySession#90]
Hi, I'm really new to raysession, and have set it up to replace the basic nsm gui. Going well so far, but I have a question about setting the osc port

It seems the osc-port is on ray-daemon, which is created by raysession, but doesn't seem to have parameters that can pass through.

I wouldn't mind starting the daemon manually, but then I haven't worked out how to connect to it from raysession, what value would I give daemon-url if I was to start ray-daemon (with a osc port) first, and then the GUI to connect to it?

What's the correct invocation to get the server to run on port 7777 and have the GUI connect to the server? Or alternatively, would it be possible to get a parameter on the GUI to pass through to the server?

Thanks!

**Comment by Houston4444** [comment]
Hi !
If a daemon is already running (on not started hidden), the GUI will automatically connect to this daemon.
So, if there is no daemon running, then you start `ray_daemon -p 7777`, then you start `raysession` and it will be connected to this daemon. In case you have many instances, raysession will connect to the first daemon started with no local GUI connected.

That said, I am curious to know the goal of a such startup, in any cases, (almost) all actions doable with oscsend to daemon are simply doable with `ray_control`. Type `ray_control --help-all` to know all things possibles. The big interest of ray_control against oscsend is that ray_control command will be finished when operation is finished. It also gives possibility to get informations in stdout.

**Comment by markjfisher** [comment]
Ah, thanks for the clarification. I'll have a go with starting daemon and session separately.

My use case is I'm just trying to find the best way to script the startup of a session, currently for nsm i was using:

    non-session-manager -- --osc-port $OSC_SERVER_PORT > /dev/null 2>&1 &
    oscsend localhost $OSC_SERVER_PORT /nsm/server/open s "$SESSION"

and wanted to replace it with something equivalent for raysession.
ray_control sounds interesting as I was doing various "sleep" commands to give oscsend time to work.

**Comment by markjfisher** [comment]
I think i'm going to have to compile this manually, the version pulled in by Ubuntu is 0.8.3 which doesn't connect to the daemon automatically, and ray_control is limited. I can see from the changelog it's got a lot more features.

**Comment by markjfisher** [comment]
That's working better now. Thanks for the information.
