### ISSUE TITLE
How can I use an absolute path for the config_file??

### ISSUE THREAD

**Issue by BrunoVernay** [Houston4444/RaySession#93]
I have an application that require an absolute path to its file. 
(It fails to save the file if it was specified as a relative path)

I tried to use `$RAY_SESSION_PATH/` but it looks like it is not expanded. 
I tried `$(pdw)/` too, without success.
I see that `$PWD/` works (thanks to https://docs.python.org/3/library/os.path.html#os.path.expandvars), but points to the RaySession root dir only.

I understand that is it not advised, but it would be great if I could either specify an absolute path in the config_file="" or if it was transformed into an absolute path during execution.

Thanks

**Comment by Houston4444** [comment]
I don't understand, here $PWD works totally and points to the proxy working dir (with ray-proxy), or to the client project path (Ray-Hack).
Note: I can't see how it could points to the RaySession root dir, at worst, it could point on start directory.

**Comment by BrunoVernay** [comment]
I checked again and $PWD points to that start directory which is in my case RaySession root dir since I use the source directly (I do a `make  LRELEASE=lrelease-qt5` only after the updates).
I start with `cd ~/l/dev/RaySession ; ./src/bin/raysession`
and $PWD points to `/home/bbb/l/dev/RaySession`

The `config_file` attribute is in `~/Music/RaySessions/Tests/test-24/Test-24.mscore/ray-proxy.xml`

I could perform other tests, if you have suggestions

**Comment by Houston4444** [comment]
Strange, it maybe comes from a different python version.
Can you try what happens if you start this with Ray-Hack protocol ? (for this, start musescore in add executable dialog unchecking "NSM Protocol" checkbox).

**Comment by BrunoVernay** [comment]
I have Python 3.8.5.
I tried your suggestion and PWD works (points to `~/Music/RaySessions/Tests/test-25/Test-25.musescore/` ) if I use it in the `Argument`, as `"${PWD}/$CONFIG_FILE"`.

Then I tried with the NSM and it work here too.  I edit the `ray-proxy.xml` file directly.  I did not try the `Arguments` field in the GUI yet.

But the point is that it works with $PWD.  It is just that some documentation should give an example, showing that: The *file name* goes in `config` and *file path* in `Argument`.

Maybe it is time to start a wiki and put these random notes and build up documentation along the way?

**Comment by Houston4444** [comment]
Ok, I understand now that the thing is you were trying PWD in config file field.

> the file name goes in config and file path in Argument

hmmm, that is not exact, file can be inside a folder, then the config_file will be `my folder/my file` and could also be outside from the working folder (even if it is strongly discouraged), and then config file can be `../another_folder/file`. Also config_file can be an absolute path (discouraged too of course).

> Maybe it is time to start a wiki and put these random notes and build up documentation along the way?

It's more than time to write a manual, sure. I first want to have a review on pulseaudio managing in jack config session scripts, and a quite big work on "Add Application" dialog, then I think I will be ready to start manual.
I really don't know how to do that now, but I want an online translatable manual, obviously, help is more than welcome in that project.
Waiting for this, we can write the needed informations about where write PWD in the qt .tooltips

**Comment by BrunoVernay** [comment]
Starting with the GitHub wiki could be quick or even straight Markdown files, that would provide the pull-request as with the code.
Python has Sphinx, but I don't know a lot about it. 
I would go for markdown files as it is simple and allow everyone to propose pull requests. (I am not sure about the wiki management )
