### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by trebmuh** [Houston4444/RaySession#95]
_(just to be sure I'm not forgetting to mention it to you)_

Using the French interface, menu -> Nouvelle session -> click on the upper right folder icon:

![traduction-raysession](https://user-images.githubusercontent.com/8705846/92665773-b0844300-f307-11ea-800e-c4d74a3c4235.png)

Note that the Cancel buttons all around the GUI aren't translated too.

**Comment by Houston4444** [comment]
Humm, this has nothing to see with RaySession.
RaySession asks Qt to ask system for a folder selection dialog.
I've not this problem with KDE, I am pretty sure that the same problem appears with all Qt programs calling a folder selection dialog. If it also happens with GTK softwares, this is typically a MATE problem. If it happens only with Qt programs, then this a problem between Qt and MATE

**Comment by Houston4444** [comment]
after short investigation, It seems that translation problem appears only with Python Qt programs.
The 1st problem (I didn't saw it), is that Qt seems to always displays native Qt file dialogs in Mate, although It offers KDE dialogs with KDE, GTK3 dialogs with Gnome... That's strange, I think I remember having test this under MATE a long time ago...
The 2nd problem (Qt native dialogs untranslated) seems to appears only with python qt softwares (RaySession, Catia...), but if the first was resolved, the 2nd would be too.

**Comment by jpcima** [comment]
Hi, it needs to install a secondary QTranslator to get the generic messages, like OK/Cancel and the like.
It's from file `qt_fr.pm` and the like, shipped in Qt itself.
see here https://github.com/falkTX/Carla/pull/860/files

**Comment by trebmuh** [comment]
Rebuild from 24a4861 and now, it's translated, thank you.
Closing then.
